### ISSUE TITLE
Usuarios con cargos públicos

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#100]
Un cargo público no tiene ningún permiso adicional ni ninguna restricción comparado con los de cualquier otro ciudadano: podrán hacer propuestas, comentar, apoyar iniciativas, etc.

La única diferencia será visual: deberá ser evidente para el resto de los ciudadanos que se trata de cargos públicos.

En la parte de la administración de la página, los administradores deberán poder añadir, editar, y borrar usuarios con cargos públicos. Hay que añadir a la tabla usuarios un campo 'official_position' que representa el cargo de este usuario. Además se definirán 5 niveles de tipo de usuario cargo público. 

Hace falta poder administrar también qué nombre poner a esos cinco niveles. En nuestra aplicación inicialmente serán:
"Alcaldes", "Concejales", "Directores generales", "Funcionariado", "Organización Municipal".

**Comment by Pi-Po** [comment]
En principio estoy de acuerdo. 
Sugerencia: Que las fotografias y los perfiles de los usuarios no puedan ser copiados y pegados en ninguna parte. Son datos públicos de libre acceso, pero nada más.
