### ISSUE TITLE
Borrar usuarios

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#103]
Desde "mi cuenta" debería poder borrar mi cuenta.
El usuario debería dar opcionalmente una razón para borrar su cuenta.
En los debates y comentarios de un usuario borrado, en lugar de su nombre, debería aparecer el texto "usuario eliminado"

Wireframes:

Mi cuenta
![delete account 1](https://cloud.githubusercontent.com/assets/4169/9109671/a8782af0-3c37-11e5-8487-234d45713515.png)

Confirmación
![delete account 2](https://cloud.githubusercontent.com/assets/4169/9109673/b0b0e720-3c37-11e5-898d-f87f115798cb.png)

Comentario de usuario borrado
![user deleted](https://cloud.githubusercontent.com/assets/4169/9109702/ec36ffaa-3c37-11e5-96d6-ac9664460a20.png)

Sugerencias: 
Crear una acción destroy para el controlador account, que utilice la gema Paranoia para marcar al usuario como borrado. Utilizar páginas completas en lugar de lightboxes. Utilizar un helper majo para mostrar que el usuario ha sido eliminado en los debates y comentarios.

Para cumplir la LOPD, aunque no borremos la instancia del usuario, debemos borrar todos los datos del usuario, que de momento son nombre, apellidos, email y nickname.

Los administradores también deberían poder borrar usuarios desde su dashboard.

**Comment by Pi-Po** [comment]
Interesante este aspecto. No obstante me surgen estas preguntas:
¿Eliminar la Cuenta significa que los datos del usuario desaparecerán del servidor?
Una vez eliminada la cuenta ¿Puede el usuario volver a acceder con sus datos eliminados?
Sugerencia: Si hablamos de "Eliminar", usar siempre esta palabra y no otra cómo "baja" (entre nosotros no hay confusión, pero a nivel de usuario puede generar dudas).

**Comment by kikito** [comment]
@Pi-Po , gracias por las sugerencias, algunas ya las íbamos a hacer y el resto las tendremos en cuenta.

Tengo dudas sobre si hace falta utilizar Paranoia aquí - principalmente porque tendríamos que reescribir el método `User.destroy` para "anonimizar" antes de que paranoia lo marcara como borrado. Pero eso es algo que puede investigar quien implemente la issue.

**Comment by decabeza** [comment]
Añadidos estilos para eliminar la cuenta de usuario en "Mi cuenta" en la rama **delete_account** en el fichero `/account/show.html.erb` y faltaría:

* Que el formulario sólo aparezca cuando el usuario haga clic en "Eliminar mi cuenta"

* Hacer funcional el formulario.

:smiley: 

Imágenes:

![delete account](https://cloud.githubusercontent.com/assets/631897/9473675/60de4e66-4b5c-11e5-8303-49c87a8c2be5.png)

![delete account form](https://cloud.githubusercontent.com/assets/631897/9473748/cb7469c2-4b5c-11e5-80c7-1a7a4c6ff4b0.png)

**Comment by decabeza** [comment]
De momento no hay campo donde guardar el texto que rellene el usuario "Motivos por los que deseas eliminar tu cuenta..." (este campo es opcional)

**Comment by voodoorai2000** [comment]
Closed via #621
