### ISSUE TITLE
Añadir breadcrumbs 

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#106]
Incluir breadcrumbs en todas las páginas antes del contenido. Ejemplo:

![breadcrumbs](https://cloud.githubusercontent.com/assets/631897/9113124/1561b738-3c53-11e5-84eb-1c96110505d6.jpg)

**Comment by apradillap** [comment]
¿Qué os parece utilizar https://github.com/weppos/breadcrumbs_on_rails?

**Comment by kikito** [comment]
La razón por la que hemos cerrado esto es: de momento, con las features que hay, no tiene sentido tener breadcrumbs (todas las opciones están a uno o dos clicks en el header). En el futuro, cuando tengamos más, habrá que plantearse reabrir esta issue.
