### ISSUE TITLE
Añadir i18n para nombres de modelos y sus atributos

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#109]
Necesitamos añadir las traducciones de los distintos modelos utilizados en la aplicación - como indica [esta sección de la guía de internacionalización](http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models)

**Comment by apradillap** [comment]
Voy a añadirlo para los modelos y sus atributos. 

Un saludo!!

**Comment by xuanxu** [comment]
Hecho [aquí](https://github.com/AyuntamientoMadrid/participacion/commit/85e3e4439c357e71e827691025d5c511436a7bf5)
