### ISSUE TITLE
Añadir Pry al Gemfile

### ISSUE THREAD

**Issue by Ferdy89** [AyuntamientoMadrid/participacion#124]
[Pry](http://pryrepl.org/) es una conocida herramienta de debugging que complementa a `byebug` y puede sustituir a `irb`. Con ella puedes hacer `cd` en objectos, `edit` sus métodos, `play` líneas individuales, y todo esto mientras el código se ejecuta.

Personalmente es una herramienta indispensable, profesionalmente lo recomiendo siempre a todo aquel que no lo haya probado. Sería genial poder tenerlo entre las herramientas de desarrollo en este repositorio.

**Comment by kikito** [comment]
Hola Ferdy89,

Gracias por tu recomendación. De momento ninguno de los core contributors utiliza Pry y no la vemos necesaria para estre proyecto. No obstante, si tú quieres utilizarla en el desarrollo, puedes hacerlo [aunque no esté incluida en en Gemfile](https://coderwall.com/p/drdcuq/use-pry-with-bundler-without-having-it-on-your-gemfile).
