### ISSUE TITLE
Eliminar gemas innecesarias

### ISSUE THREAD

**Issue by Ferdy89** [AyuntamientoMadrid/participacion#125]
[Jbuilder](https://github.com/AyuntamientoMadrid/participacion/blob/master/Gemfile#L21) no parece estar siendo usado, de modo que mejor eliminarlo para evitar tener que mantenerlo.

En la misma línea, nadie parece estar usando `sdoc`, especialmente porque genera la documentación en `/doc`, pero el directorio no está en el `.gitignore`. De ser así el caso, mejor eliminarlo también, pudiendo dejar abierta la alternativa a otras herramientas de documentación si se quisiera.

**Comment by kikito** [comment]
Todavía falta eliminar `sdoc`
