### ISSUE TITLE
Mover el capa de presentación fuera de los modelos

### ISSUE THREAD

**Issue by Ferdy89** [AyuntamientoMadrid/participacion#126]
En en el [modelo User](https://github.com/AyuntamientoMadrid/participacion/blob/master/app/models/user.rb#L12) empieza a verse código relativo a la presentación de los datos en el modelo. Es habitual ver cómo al comienzo de una aplicación en Rails se ponen estos métodos directamente en el modelo por comodidad y para cuando se quiere introducir una nueva y concreta capa de presentación, la refactorización resulta dolorosa.

Hay gemas como [Draper](https://github.com/drapergem/draper) que ayudan mucho en el proceso, pero el realidad muchas veces no es necesario: basta con crear un directorio donde colocar los presentadores (o decoradores) `app/presenters` o `app/decorators`, que los presentadores sean delegadores al modelo `class UserPresenter < SimpleDelegator` y pasar presentadores a las vistas, no instancias del modelo `@user = UserPresenter.new(@user)`.

Los presentadores a menudo ayudan a cubrir la distancia entre el modelo y la vista, convirtiéndose el POROs testeables y organizados.

**Comment by voodoorai2000** [comment]
Estamos de acuerdo @Ferdy89 pero de momento preferimos no añadir una capa más.
