### ISSUE TITLE
Creación y destrucción de moderadores

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#134]
Los administradores deben ser capaces de promover usuarios comunes a moderadores, y viceversa, desde su dashboard de administración

**Comment by jmgcrespo** [comment]
Si nadie está con este, me gustaría hacerlo yo.

**Comment by voodoorai2000** [comment]
Toda tuya @jmgcrespo!

**Comment by kikito** [comment]
hey @jmgcrespo, ¿sigues con esto, o nos ponemos nosotros?

**Comment by jmgcrespo** [comment]
Está casi listo a falta de los tests,  os envío esta noche el PR.

**Comment by kikito** [comment]
Ok, muchas gracias!

**Comment by xuanxu** [comment]
Hecho en #239
