### ISSUE TITLE
Ocultar Debates, Comentarios, Etiquetas y Usuarios

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#136]
La función principal de los moderadores es hacer que las discusiones se hagan siguiendo unas normas básicas de respeto. Por ejemplo, no se permitiría ni SPAM ni comentarios racistas o xenófobos.

Los moderadores deben poder ocultar (sin borrar) debates, comentarios, etiquetas y usuarios. Los moderadores también pueden "desocultarlos".

Es preferible ocultar un comentario que un debate, y un debate que un usuario. 

Cuando un debate es marcado como oculto:
* No aparece en los listados de los ciudadanos comunes
* Al ocultarlos, los moderadores deben añadir una razón ("Anuncio de producto")
* Los moderadores pueden verlos en su dashboard de administración, en una zona de "Debates Ocultos", y hacer un "show" del debate.
* Los usuarios no moderadores no pueden hacer "show" del debate.

Cuando un comentario es marcado como oculto:
* Los ciudadanos comunes no lo ven, ni pueden hacer "show" a él con un link directo.
* Los moderadores ven "ocultado por incumplir las normas"
* Los moderadores pueden "abrirlo" para leer su contenido, y "desocultarlo ahí mismo"

Cuando una etiqueta es marcada como oculta:
* Los ciudadanos comunes no la ven, ni pueden listar Debates con esa etiqueta (el listado es vacío).
* Los moderadores la pueden ver en un listado en su dashboad.
* Los moderadores pueden desocultar etiquetas.

Cuando un usuario es marcado como oculto:
* Éste sería el último recurso, reservado principalmente para usuarios de SPAM
* Cuando un usuario es marcado como oculto, todos sus comentarios y debates son marcados como ocultos.
* Los moderadores tienen un listado en el que pueden ver los usuarios ocultos, sus debates, y sus comentarios.
* Cuando un usuario es "desmarcado como oculto", sus debates y comentarios volverán a ser visibles, a no ser que ya estuvieran marcados como ocultos anteriormente.

**Comment by voodoorai2000** [comment]
Closed via #185 
Continued at #186

**Comment by kikito** [comment]
Reabro esta issue para preguntar: con la PR #185 se ha conseguido que los *administradores* puedan moderar (los controles y los permisos están en `/admin/`, no en `/moderate/`)

@xuanxu, @voodoorai2000 : no deberían los moderadores ser los que tienen acceso a esto?

**Comment by xuanxu** [comment]
Tal como está ahora los moderadores pueden ocultar, y solo los administradores pueden des-ocultar.

**Comment by kikito** [comment]
Ok. Me había despistado el hecho de que los moderators no tuvieran nada en `/moderate` - pero ya veo que pueden bloquear cosas directamente "en la interfaz normal". Tiene sentido si no pueden hacer "undo".

Creo que el botón de bloquear usuario está demasiado a mano - un poco [ejector seat level](http://blog.codinghorror.com/the-opposite-of-fitts-law/). Pero eso es para otra issue.
