### ISSUE TITLE
Al comentar desaparece el form y al recargar se ordenan mal

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#142]
Ahora funciona así:
* En debates/shows al publicar un comentario el form desaparece. 
* Sólo vuelve a aparecer si recargamos la página.
* Cuando se publica un comentario aparece el primero pero al recargar la página los ordena de antiguos a nuevos.

Y así es como debería funcionar:
* Si el usuario está logueado el form de comentar debería aparecer siempre.
* Los comentarios siempre deberían estar ordenados de nuevos a antiguos.

**Comment by dgilperez** [comment]
Hola @decabeza !!! 

Me alegro de verte por aquí. Aquí va un PR para celebrarlo :smile:

**Comment by decabeza** [comment]
¡Hola @dgilperez! 

¡Encantado también de tenerte por aquí! :+1:

**Comment by dgilperez** [comment]
Pues esto también está :+1:
