### ISSUE TITLE
Incluir número total de respuestas y votos en comentarios

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#143]
- Añadir el "número total de respuestas" de un comentario en "/comments/_comment.html.erb"
- Añadir el "número total de votos" de un comentario en "/comments/_votes.html.erb"

![total reponses and votes](https://cloud.githubusercontent.com/assets/631897/9196500/2cdc4c5c-402c-11e5-83ed-5c677090c2c0.png)

**Comment by dgilperez** [comment]
Me gustaría hacer este también, si os parece OK

**Comment by voodoorai2000** [comment]
Por supuesto @dgilperez, adelante! Muchas gracias!

**Comment by dgilperez** [comment]
Pues creo que ya está listo!
