### ISSUE TITLE
Limitar número de etiquetas mostradas

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#144]
En los listados de debates deberían aparecer sólo las primeras 5 etiquetas, después mostrar una con "+n". 

- Si el usuario pulsa en una de las 5 primeras se filtran los debates que contengan esa etiqueta.
- Si el usuario pulsa en "+n" le lleva a debates/show donde puede ver todas las etiquetas asignadas a ese debate.

![n tags](https://cloud.githubusercontent.com/assets/631897/9196977/d72de3a6-4030-11e5-9acb-b885b35b5159.png)

**Comment by dgilperez** [comment]
Ahí va otra!

**Comment by voodoorai2000** [comment]
Closed via #149
