### ISSUE TITLE
Arreglar posible vulnerabilidad con las etiquetas

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#15]
Asegurarse que no se puede meter código malicioso. 
Comprobar:
- [x] Controlador Debates
- [x] Nube de etiquetas
- [x] Helper Tag list

**Comment by kikito** [comment]
La nube de etiquetas y el helper tag list utilizan `sanitize` (+ el html_safe de rails) como capa adicional de protección para evitar invocaciones de javascript.
