### ISSUE TITLE
Utilizar tablespaces en nuestros esquemas 

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#152]
Las bases de datos del ayuntamiento tienen algunas características especiales. Una de ellas es que las tablas que utilizan están separadas en [tablespaces](http://www.postgresql.org/docs/9.2/static/manage-ag-tablespaces.html).

En nuestro caso:
* El tablespace `ts_participacion_dat01` es donde van los las "tablas normales"
* El tablespace `ts_participacion_lob01` es para tablas que tengan algún campo de tipo LOB (text, binary json...)
* El tablespace `ts_participacion_idx01` es donde van los índices

Sugerencias:
* Añadir una migración que cree (si no existen) los tablespaces, usando sql
* Añadir una segunda migración que mueva las tablas y los índices existentes en el schema a su tablespace correspondiente (quizá con sql también)

Nice to have:
* Añadir un test que recorra las tablas y los índices y se asegure de que cada tabla está en el tablespace adecuado (esto permitiría detectar problemas en nuestros propios commits y también en pull requests que nos hagan)

La orden para crear una tabla dentro de un tablespace es usando `options`:

```
create_table :session_logs, :id=>false, options: ‘TABLESPACE ngn1_log’ do |t|….
```

No sé si `options` también puede funcionar en `change_table`; si no habría que cambiarlos con sql en las migraciones.

**Comment by voodoorai2000** [comment]
Does not seem to be a performance problem.
