### ISSUE TITLE
Cambiar switch de idiomas por un select

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#155]
Hay que cambiar el `<span id="locale-switcher">` en `layouts/_header.html.erb` por un form > select.

Foundation tiene también un dropdown que funciona con JS http://foundation.zurb.com/docs/components/dropdown.html pero en su documentación indica que no es accesible "This component is not yet accessible. Stay tuned for updates in future releases."

Se podría incluir bien uno que no de problemas en ningún navegador o la idea del select.

![switch language](https://cloud.githubusercontent.com/assets/631897/9225781/8c88abfc-410b-11e5-9473-b0bfd3717b49.png)

![switch language active](https://cloud.githubusercontent.com/assets/631897/9225802/9fb4f14a-410b-11e5-9df0-5583713fe9f5.png)

**Comment by kikito** [comment]
@decabeza pregunta de UX aquí: 

* ¿Incluimos el "idioma en el que se está" en el select? (p.ej. si estamos en español, en el select debería aparecer el español?
* En el caso de que se incluya el idioma actual en el select, ¿no debería estar pre-seleccionado el idioma actual (en lugar de tener una entrada extra llamada "Idioma de la página" en el select)?.
* ¿Prefieres el nombre del idioma entero en lugar del código del idioma (EN, ES, ...)?

**Comment by decabeza** [comment]
@kikito hay varias opciones, según lo fino que queramos hilar:

* La más "usable" es mostrarlo todo, es decir, "Idioma de la página: español" (muestra qué es el select y cual esta seleccionado)

* Se puede mostrar sólo "Idioma de la página" y el desplegable con los idiomas y un check en el seleccionado.

* Por último otro que ocupa menos espacio es sólo el idioma "español" pero puede llevar a confusión si es el idioma o el "portal" en sí.

Me decantaría por una de las dos primeras, aunque creo que tratándose de una página oficial con especial atención a la accesibilidad, sin duda es la primera. 

En ningún caso usaría el código del idioma, siempre el nombre y a poder ser en su propio idioma. Aunque estemos en español el listado debería ser por ejemplo: español, english, italiano, français...

**Comment by kikito** [comment]
@decabeza te propongo entonces que "Idioma de la página" sea un label en lugar de parte del select:

```
Idioma de la página: [ Español ▼ ]
```

**Comment by decabeza** [comment]
@kikito perfecto! :+1:

**Comment by kikito** [comment]
Ok, me asigno esto y te lo devuelvo cuando haya que ponerle estilos ^^

**Comment by xuanxu** [comment]
Solo queda cambiar los estilos así que cerramos este issue en favor de #204
