### ISSUE TITLE
Incluir initial JS para mostrar el avatar del usuario 

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#156]
Incluir http://judelicio.us/initial.js/ para mostrar el avatar del usuario y quitar las imágenes de ejemplo `user_default.jpg`, `user_default_2.jpg` y `user_default_big.jpg` que ahora mismo aparecen en:

* Mi cuenta: `account/show.html.erb`
* Debate: `debates/show.html.erb`
* Comentarios: `comments/_comment.html.erb`

**Comment by dgilperez** [comment]
Interesante plugin, me lo apunto! 

Me lo cojo ;)

**Comment by dgilperez** [comment]
Listo!

**Comment by voodoorai2000** [comment]
Closed via #158
