### ISSUE TITLE
Bug en comentarios: responder varias veces al mismo comentario no funciona

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#160]
Pasos para repetir:

* Comentar en un debate (Comentario 1)
* Responder al Comentario 1 (Pulsando "responder" y rellenando el formulario)
* Volver a responder al Comentario 1 (Pulsando "responder")

Qué ocurre:
* El diálogo de "responder a comentario 1" no aparece

Qué debería ocurrir:
* Debería ser posible responder al Comentario 1 varias veces.

**Comment by dgilperez** [comment]
Hey @xuanxu, como esto está relacionado con este otro PR https://github.com/AyuntamientoMadrid/participacion/pull/158, estaba jugando con ello y creo que lo he resuelto.

**Comment by xuanxu** [comment]
hey @dgilperez, gracias tío!
Me has pillado haciéndolo y lo acabo de subir, creo que lo he dejado un poco más limpio y con los tests en verde.

**Comment by dgilperez** [comment]
Correcto, la otra parte es para cuando se incluya `App.Comments.initialize()` en un `on ajax:complete`, que al final aquí no es el caso.
