### ISSUE TITLE
Integrar Ckeditor (wysiwyg)  con Turbolinks

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#166]
Pasos para reproducir:

* Ir a la página de nuevo debate.
* Cambiar de idioma.

Qué ocurre:
* El editor de la descripción del debate desaparece.

Qué debería ocurrir:
* El editor de la descripción debería aparecer, marcando los *hints* de sus botones en el idioma correspondiente.

**Comment by xuanxu** [comment]
En el peor de los casos si no encontramos la manera de resetear el ckeditor, se puede hacer que el link de cambio de idioma no use turbolinks: `<span id="locale-switcher" data-no-turbolink>`

**Comment by kikito** [comment]
Issue relacionada abierta en la gema de ckeditor: https://github.com/galetahub/ckeditor/issues/575

**Comment by kikito** [comment]
He conseguido arreglar parte del problema haciendo esto (basándome en que nuestros ckeditors siempre van dentro de un div con clase ckeditor):

```
  $(document).bind('page:change', function() {
    $('.ckeditor textarea').each(function() {
      CKEDITOR.replace($(this).attr('id'), { language: document.documentElement.lang });
    });
  });
```

Esto funciona casi bien, pero no del todo - el idioma no cambia. Podría actualizarlo si el atributo html del html se cambiara, pero lamentablemente turbolinks no lo hace:

https://github.com/rails/turbolinks/pull/385#issuecomment-50841638

Creo que esto ya da demasiados problemas. Voy a hacer una PR que desactive turbolinks en el locale switcher.
