### ISSUE TITLE
Comentarios de moderadores y administradores

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#170]
Los moderadores deberían poder escoger si escribir un comentario como moderador. Ese comentario debería salir escrito con un nombre genérico "Moderador" y resaltado de alguna forma.

Sugerencia: 

Si estás identificado como un moderador, mostrar un checkbox en el formulario de comentarios para marcar que ese mensaje debería ser escrito como el de un moderador. 

Marcar el comentario con una clase css especial para identificarlo como 'escrito por un moderador'

**Comment by decabeza** [comment]
Añadido checkbox para **comentar como moderador**. Subido a la rama **moderator_comments**

**Pendiente para hacer que funcione:**

* Checkbox en `comments/_form.html.erb` (hacer funcionar el checkbox de “Comentar como moderador”)

* Condiciones en `comments/_comment.html.erb` (que el usuario sea moderador y haya seleccionado el checkbox)

* Además, hay que hacer que cuando un moderador comente pierda todos los badges asociados que tenga (cargo oficial, grupo o colectivo,…) para que sea un **comentario totalmente anónimo**.

**Tener cuidado con aquellos comentarios** del código en los que aparece “comment.user.hidden?”, estos están relacionados con #103 

Imágenes del resultado:

![checkbox_comment_as_moderator](https://cloud.githubusercontent.com/assets/631897/9363083/8dc6d630-46a4-11e5-88d8-eed4f99fc5dd.png)

![comment_as_moderator](https://cloud.githubusercontent.com/assets/631897/9363087/92050f64-46a4-11e5-8287-8510a5b6a17d.png)

**Comment by decabeza** [comment]
He subido nuevos cambios a la rama **moderator_comments** con estilos para "comentar como administrador" que funciona exactamente igual que el de los moderadores.

Además de la lista del comentario anterior, hay que añadir:

* En el nombre de usuario de moderador/administrador añadir un `#ID` para poder diferenciarlos.

Imágenes del resultado final:

* Administradores:

![comment_as_admin](https://cloud.githubusercontent.com/assets/631897/9423185/fd44cb22-48b9-11e5-96b7-020c0a725309.png)

![comment_as_admin_form](https://cloud.githubusercontent.com/assets/631897/9423186/ffb535f4-48b9-11e5-9906-823c87497660.png)

* Moderadores:
![comment_as_moderator](https://cloud.githubusercontent.com/assets/631897/9423183/ee3d9d7a-48b9-11e5-8408-1fab5a72805f.png)

![comment_as_moderator_form](https://cloud.githubusercontent.com/assets/631897/9423184/f5ea3be6-48b9-11e5-9715-72f52e931ce2.png)
