### ISSUE TITLE
Reportar contenido

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#171]
Cualquier usuario debería poder reportar contenido que crea que no es apropiado y por tanto que debería ser revisado/eliminado por un moderador.

Sugerencia:

Mostar un link 'reportar' en cada comentario y debate.

Marcar estos comentarios, debates como reportados en la base de datos, y mostrarlos en la zona de Moderación.

(Los moderadores deberían poder 'ocultar' ese contenido 'reportado' #136)

Los moderadores deberían poder marcar el contenido 'reportado' como 'revisado'. Ese contenido debería pasar entonces a otra lista visible sólo para moderadores, lista de 'revisados'.

**Comment by kikito** [comment]
Un par de preguntas:

* Los usuarios no deberían poder reportar cada cosa más de una vez, ¿verdad? En tal caso deberíamos guardar quién ha reportado qué (y así mostrar un "ya has reportado" en lugar del botón de reportar)
* ¿Qué hacemos cuando un comentario o debate es marcado como 'revisado', pero sigue recibiendo reports? Hay dos opciones: ignoramos los reports o le quitamos el flag de revisado para que se vuelva a mirar. Si le quitamos el flag a lo mejor podemos usar un campo `reviewed_at` para la revisión y un `last_flagged_as_inappropiate_at` (no sé si con su campo propio en la db), y comparar las dos fechas.

Y un par de consideraciones:
* Tenemos que encontrar un nombre mejor de "report" para esto. Propongo "Marcar como inapropiado / Flag as inappropiate". El nombre de la base de datos/modelo podría ser `InappropiateFlag` (no me gusta mucho porque Inappropiate es difícil de escribir)
* Creo que sería deseable que los moderadores pudieran ordenar los comentarios y debates por "número de reports"
* Creo conveniente fusionar esto con el menú de moderación (en lugar de crear una página aparte separada únicamente para filtrar por flags)

**Comment by xuanxu** [comment]
>  Los usuarios no deberían poder reportar cada cosa más de una vez, ¿verdad? En tal caso deberíamos guardar quién ha reportado qué (y así mostrar un "ya has reportado" en lugar del botón de reportar)

Correcto, los usuarios no pueden reportar una cosa más de una vez. En cuanto a qué hacer con lo ya reportado, podemos mostrarle el icono de la bandera activa como indicación de que lo ha denunciado y para que pueda pinchar y "des-desnunciarlo". 

> ¿Qué hacemos cuando un comentario o debate es marcado como 'revisado', pero sigue recibiendo reports? Hay dos opciones: ignoramos los reports o le quitamos el flag de revisado para que se vuelva a mirar. Si le quitamos el flag a lo mejor podemos usar un campo reviewed_at para la revisión y un last_flagged_as_inappropiate_at (no sé si con su campo propio en la db), y comparar las dos fechas.

Yo daría el poder a los moderadores: que puedan marcar el comentario como 'revisado' (le quita el estado 'denunciado'), o si ven que les vuelve a aparecer y no quieren que lo puedan marcar como 'no denunciable' (ya no aparecería la banderita o se ignorarian las denuncias).

> Y un par de consideraciones:
> Tenemos que encontrar un nombre mejor de "report" para esto. Propongo "Marcar como inapropiado / Flag as inappropiate". El nombre de la base de datos/modelo podría ser InappropiateFlag (no me gusta mucho porque Inappropiate es difícil de escribir)

+1 a esos nombres (o incluso "Denunciar como inapropiado", para que se note que es una acción 'fuerte' a usar con criterio). En la bd/modelo, yo creo que Flag nos vale.

> Creo que sería deseable que los moderadores pudieran ordenar los comentarios y debates por "número de reports"

+1

>Creo conveniente fusionar esto con el menú de moderación (en lugar de crear una página aparte separada únicamente para filtrar por flags)

+1

**Comment by kikito** [comment]
+1 a "Denunciar" en lugar de "Marcar", gracias.

He estado "de caza" y he encontrado [make_flaggable](https://github.com/medihack/make_flaggable). Utilizan un nombre un poco "peculiar" para las denuncias: *flaggins*. Pero lo prefiero sobre únicamente *flags* porque tiene un significado demasiado amplio (si llegamos a tener [feature flags](https://en.wikipedia.org/wiki/Feature_toggle), por ejemplo). Como tenemos algunas características un poco especiales (el "marcar como revisado") a lo mejor simplemente copio partes de la gema.
