### ISSUE TITLE
Admin CRUD para temas habituales 

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#172]
Los administradores deberían poder definir una lista de Temas (Economía, Hacienda, Medio ambiente) que saldrán como opciones, a la hora de crear un nuevo debate.

Sugerencia:

CRUD de Temas en la zona de administración.
(Mostrar estos temas en la página de nuevo debate #67)

**Comment by dgilperez** [comment]
@voodoorai2000 te parece bien extender la clase `ActsAsTaggableOn::Tag` añadiéndole un campo extra `featured` en base de datos?

**Comment by voodoorai2000** [comment]
@dgilperez Sí, creo eso cubriría los requerimientos ;)

**Comment by xuanxu** [comment]
Closed in #176
