### ISSUE TITLE
Número máximo de votos anónimos por debate

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#173]
Los usuarios que sólo se han registrado con su email o a través de redes sociales, son considerados usuarios anónimos. (Para dejar de ser anónimo, habrá que verificar a los usuarios por SMS y por el Padrón de Madrid).

Un debate sólo deberá poder tener un porcentaje máximo de votos anónimos. A partir de ese porcentaje, se debe mostrar un mensaje diciendo que hay demasiados votos anónimos (como en menéame) y que el usuario debe verificar su cuenta (SMS y Padrón) para votar.

**Comment by decabeza** [comment]
Añadidos estilos en la rama **anonymus_votes**

**Pendiente de cambiar** el enlace a "verifica tu cuenta" en `/debates/show.html.erb` y que la alerta sólo aparezca cuando haya demasiados apoyos anónimos :smile: 

Imagen del resultado:

![anonymous_votes](https://cloud.githubusercontent.com/assets/631897/9423374/8fe9a270-48c1-11e5-8221-341cbacb038e.png)

**Comment by decabeza** [comment]
Cuando esté lista la parte de verificar tu cuenta habría que añadir el enlace aquí.

Falta por definir cual es el número de votos anónimos que admite un debate antes de que salte la alerta :smile:

**Comment by voodoorai2000** [comment]
El porcentaje de votos anónimos debería ser configurable, de forma predeterminada 50%.

**Comment by xuanxu** [comment]
@decabeza: Tengo esto listo pero necesito cambios en el diseño:
Lo que subiste es una alerta a mostrar en la página de debate cuando haya demasiados votos anónimos. Creo que sería mejor que fuera una capita que apareciera sobre los votos (en caso necesario), exactamente igual que [funciona ahora para usuarios no registrados](https://github.com/AyuntamientoMadrid/participacion/blob/master/app/views/debates/_votes.html.erb#L24-L30): al hacer over en los votos aparece esto:
![captura de pantalla 2015-08-31 a las 17 33 39](https://cloud.githubusercontent.com/assets/6528/9582588/85e41d4a-5006-11e5-805d-8cbd40863779.png)

Y al igual que con eso, hace falta que funcione en todos los diseños: el index de debates, y el index general (featured_debates), no solo en el show. Puedes meterlo [aquí](https://github.com/AyuntamientoMadrid/participacion/blob/master/app/views/debates/_votes.html.erb#L23) y luego lo hago yo funcionar?

Tienes tus cambios en la rama anonymous-votes (he borrado la que tu subiste, esta es lo mismo pero con un rebase a master actual).

**Comment by decabeza** [comment]
@xuanxu acabo de subir a **anonymous-votes** los estilos para esto :tada:
