### ISSUE TITLE
Diseño zona admin/moderación

### ISSUE THREAD

**Issue by xuanxu** [AyuntamientoMadrid/participacion#183]
Hace falta meter diseño a la zona de admin y moderación.
Ahora mismo lo que hay está sin diseño o con html provisional, haría falta una estructura general de menus/pestañas o similar para ir añadiendo secciones y luego además al menos diseño para formularios, cajas de búsqueda y listados.

**Comment by decabeza** [comment]
Closed by 0c2901c3fb4f7c9b4f7d26df2166255ece94bb10
