### ISSUE TITLE
Diseño de organizaciones

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#188]
Una vez que #182 esté mergeada, están los siguientes elementos de diseño pendientes de hacer:

- [x] Las organizaciones tienen que tener un "distintivo" cuando la organización está verificada/rechazada/pendiente de verificación (para los desarrolladores: eso se calcula haciendo `user.organization? && user.organization.verified?` - recomendable hacer un `LEFT JOIN` con las organizations si hay que listar usuarios, e.g. en comentarios). Relacionado con #24
- [x] La página de "Mi cuenta" es distinta para organizaciones (tiene menos campos). Revisar que esté ok.
- [x] Low-priority: La página de administración de organizaciones (`/admin/organizations`) no tiene estilos.

**Comment by decabeza** [comment]
Cerrado por 908d19e2e7f31f9cd2e7c0e221dc3015c21014d2
