### ISSUE TITLE
Autenticación con redes sociales

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#19]

**Comment by juandefelix** [comment]
Hola, me gustaría poder desarrollar el código para este "issue". Me imagino que lo queréis hacer con la estrategia `omniauthable` de Devise. Os puedo crear el acceso por Facebook.

**Comment by xuanxu** [comment]
@juandefelix gracias por el interés. Efectivamente pensabamos en hacer esto con devise + omniauth así que adelante. 

El único requisito sería que si creas una aplicación en FB para hacer pruebas, no quede luego rastro en el repo (urls, ni claves de autenticación).  Es decir, ese tipo de datos no queremos que estén en archivos tipo secrets.yml.example y no deberían ser críticos para ejecutar la aplicación en local (o sea, el resto de cosas deberían funcionar) y el que quiera probar esta funcionalidad se debe crear su propia app con sus respectivas claves.

**Comment by juandefelix** [comment]
@xuanxu De acuerdo! Me pongo a ello...

**Comment by uira** [comment]
Hola amigos, 

Soy de Brasil e estamos dejarollando um Identity Provider federado, para la autenticacion del cidadano en todos los serviços públicos dogitales, com la mesma identidade digital openid connect powered.

http://logincidadao.org.br/

E http://github.com/PROCERGS/login-cidadao/

**Comment by kikito** [comment]
Hola @uira,

*Muito obrigado!*

ES: La autenticación de los usuarios es una de las tareas más complejas que tenemos que hacer.  Todavía estamos lejos de poder usar un *Identity Provider*, pero lo estudiaremos.

EN: Authenticating users is one of the most complex tasks that we'll have to do. We're still far away from being able to use an Identity Provider, but we'll study it.

**Comment by uira** [comment]
Gracias @kikito,

Hemos estado trabajando durante casi dos años en este proyecto, abrimos el código desde los primeros dias, porque creemos que la demanda para crear Proveedores Federados de identidad es una demanda común para todas las democracias.

Tenemos un grupo de 80 personas que trabajan en este proyecto y es una gran oportunidad para construir una colaboración entre los hackers de la política de Brasil - España. (Para unirse a nuestro grupo Telegrama: bit.ly/LoginCidadaoNoTelegram)

Actualmente los gobiernos de todo el mundo han privatizado Identificación Ciudadana usando herramientas de Google, Twitter y Facebook. La "Conexión Ciudadana" es una herramienta para dar a los ciudadanos y los gobiernos el control sobre sus identidades y la información ciudadana.

Si quieren acelerar el proceso, podemos hacer una videoconferencia. Estoy seguro de que nuestro equipo puede ayudar a conectar las herramientas actuales en un proveedor de identidad abierta, en menos de una semana ;)

Gracias por los comentarios y felicitaciones por la iniciativa maravillosa.

**Comment by dgilperez** [comment]
Hey @juandefelix, si tienes alguna duda con esto puedo echarte un cable, lo acabo de implementar para un side-project y lo tengo fresco.

**Comment by juandefelix** [comment]
Hola @dgilperez, perdona por la tardanza en contestar, estaba de vacaciones. Si tengo alguna duda, te pregunto. Me imagino que también podrás añadir algo al código una vez hecho el pull request, si quieres añadir algo.

**Comment by dgilperez** [comment]
@juandefelix perfecto!

**Comment by kikito** [comment]
Hola @juandefelix , así que voy a abrir esta issue a que otros nos manden sus pull requests. Espero que no te importe (tú puedes seguir trabajando en ello y mandarnos la tuya si quieres).

@dgilperez, ¿nos podrías mandar tu versión de esta PR?

**Comment by dgilperez** [comment]
Yeah @kikito ! Creo que esta tarde podré echarle un rato, quizás pueda mandar algo. 

Preguntas: 

* Qué proveedores de oauth? Facebook + Twitter + Google? Alguno más? Alguno menos?
* ¿Me pasáis credenciales de develop para montar las apps correspondientes en cada plataforma?

**Comment by dgilperez** [comment]
Me respondo yo a la segunda, del primer comentario de @xuanxu: se monta con credenciales propias y después vosotros configuráis los accesos definitivos.

**Comment by kikito** [comment]
@dgilperez

> Facebook + Twitter + Google? Alguno más? Alguno menos?

Con esos tres nos vale. Si puedes añadir Whatsapp también, bien. Si no, no pasa nada.

**Comment by juandefelix** [comment]
@kikito Sin problema

**Comment by decabeza** [comment]
@dgilperez para autenticarse es necesario: Facebook, Twitter y Google. Whatsapp es para la opción de "Compartir en..." (que será otro issue) :wink:

**Comment by kikito** [comment]
Confirmo que Whatsapp es solo para compartir, no para autenticarse. Se me ha ido la pinza, disculpad.

**Comment by dgilperez** [comment]
jajaja sin problemas. Y qué hacemos con las organizaciones? Que se registren con OAuth también, o esperamos a tener eso más claro? De momento está habilitado solo para usuarios normales.

**Comment by kikito** [comment]
Correcto, @dgilperez : las organizaciones que se registren solamente con su formulario de organizaciones, sin red social.

**Comment by voodoorai2000** [comment]
Closed via #238
