### ISSUE TITLE
Añadir filtros a los debates

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#193]
Los filtros deberían ser **Estás viendo los debates**:

- Más nuevos: ordenados por fecha de creación
- Más votados: mayor número de votos
- Mejor valorados: mayor número de votos positivos

También se debería poder filtra por tema:

- Estás viendo N debates con el tema 'X'

**Diseño de ejemplo en `/debates/index.html.erb`**

**Comment by decabeza** [comment]
Resultado final de filtros:

![debates filter](https://cloud.githubusercontent.com/assets/631897/9423059/80667b7e-48b3-11e5-94d1-69fd05953abf.png)

Filtrar por tema:

![debates filter topic](https://cloud.githubusercontent.com/assets/631897/9423060/854ef206-48b3-11e5-810f-197760624388.png)

**Comment by mlovic** [comment]
Hola, me gustaría hacer este, si os parece bien.

**Comment by decabeza** [comment]
:+1: @mlovic ¡adelante! y si te animas hay otro similar para los comentarios #227 :wink:

**Comment by mlovic** [comment]
Los filtros para ordenar ya están en master (#254). El filtro para temas lo acabo de hacer. Se tendrá que poder filtrar por tema y ordenar a la vez no? Ahora está así:

![selection_021](https://cloud.githubusercontent.com/assets/7111622/9544872/82b7f120-4d84-11e5-9b3d-1a9fa34c6e71.png)

**Comment by mlovic** [comment]
Se me ocurre hacerlo así:

![selection_024](https://cloud.githubusercontent.com/assets/7111622/9545040/32774dbc-4d86-11e5-882b-a917f7ade7a0.png)

**Comment by decabeza** [comment]
@mlovic la verdad que eso lo habíamos dejado como una feature para más adelante, pero si lo incluyes ya perfecto :smile: :+1:

**Comment by xuanxu** [comment]
+1

**Comment by mlovic** [comment]
Listo, menos por los estilos  #275

**Comment by voodoorai2000** [comment]
Closed via #275 #254
