### ISSUE TITLE
Error cuando no se tiene PhantomJS instalado

### ISSUE THREAD

**Issue by jjballano** [AyuntamientoMadrid/participacion#196]
Lanzando los tests me daban muchos errores al principio y he visto que me faltaba tener instalado PhantomJS, que no está como uno de los prerequisitos ni como gema.
Yo me lo he instalado con npm directamente, pero puedo probar alguna gema o modificar el readme y hacer un pull request si queréis :)

**Comment by voodoorai2000** [comment]
Hola Jesus!
Me alegro de verte por aquí :)

Efectivamente es una dependencia no documentada, si por favor, márcate un pull.
Si al final lo pones en el Readme, mejor ponerlo en la sección de tests.

**Comment by jjballano** [comment]
He probado a añadir esta gema https://github.com/colszowka/phantomjs-gem y los tests me van bastante lentos. He probado a quitarla y me siguen yendo lentos, alrededor de 3 minutos para ejecutar la suit entera. Creo recordar que antes de añadir la gema me iban mucho más rápido, pero entre medias también me he actualizado el fork con lo que habéis añadido estos últimos días.

Me podéis confirmar que los tests se llevan ese tiempo más o menos? No querría cargarme el rendimiento de los tests ;)

**Comment by voodoorai2000** [comment]
Hemos visto que los tests iban muy lentos con versiones antiguas de phantomjs. Con la última versión todos los tests deberían tardar unos 20 segundos.

**Comment by jjballano** [comment]
Ok, puede ser ese el motivo entonces. Le echo un ojo antes de hacer el pull request.

**Comment by kikito** [comment]
@jjballano : a mí me pasaba justo eso. Tenía una versión antigua de phantomjs instalada que no se desinstalaba con `brew install phantomjs` - me decía que estaba instalada la 2.0.0 pero al ejecutar `phantomjs --version` decía `1.9.8`. He tenido que hacer un `which phantomjs` y borrar el fichero para que me reconociera el nuevo phantomjs instalado por brew.

**Comment by voodoorai2000** [comment]
@jjballano con que añadas a la sección de tests en los READMEs que hace falta la versión de PhantomJS >= 2.0 ya nos va perfecto.

**Comment by jjballano** [comment]
La gema instalaba la 1.9.8 y npm también, por lo que al final está añadido en los READMEs.

**Comment by voodoorai2000** [comment]
Closed via #196
