### ISSUE TITLE
Diseño de paginación

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#205]
Ya tenemos paginación ( #201 ) pero necesita estilos.

Sitios donde hay paginación de momento:

* Debates#index
* Comments (1st level) in debates#show
* Admin/Organizations
* Admin/Tags
* Admin/Debates
* Admin/Comments

**Comment by decabeza** [comment]
Cerrado por 2b6ea3a40f4bf977fca440369589a79abd55568d, sin querer he creado un nuevo issue con esto al hacerlo #207
