### ISSUE TITLE
Reordenar temas del sidebar

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#225]
Los temas del sibedar deberían estar ordenados:

* 1) Número de debates que contienen esa etiqueta.

* 2) Si es el mismo número, orden alfabético.

También **hay que revisar** que ahora una etiqueta que marca "N debates" si filtramos por ella solo aparecen n-1.

![sidebar topics](https://cloud.githubusercontent.com/assets/631897/9429021/7f94b908-49c2-11e5-8fdb-f8614bda4716.png)

**Comment by jjballano** [comment]
Seguramente no me esté dando cuenta de algo, pero no entiendo la última frase de revisar el número en la etiqueta si filtramos por ella.
Según entiendo, si filtro por animales, en vez del 9, me debería de aparecer un 8. Por qué motivo?
Qué pasa con las que tienen un 1? Desaparecen o aparecen con un 0?

**Comment by decabeza** [comment]
@jjballano lo que pasa ahora (no sé por qué) es que cuando filtras por un tema, por ejemplo animales que indica "9" solo se muestran 8 debates con esa etiqueta (aunque en la etiqueta siempre pone 9)

**Comment by jjballano** [comment]
@decabeza ok! no lo había entendido.
Si no corre mucha prisa, me pongo con esto durante el finde :)

**Comment by decabeza** [comment]
Perfecto, ¡gracias! :+1:

**Comment by jjballano** [comment]
Se me olvidó comentar que lo de que salgan n-1 debates a mi no me ocurre

**Comment by xuanxu** [comment]
esto está hecho
