### ISSUE TITLE
Registro de organizaciones / colectivos

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#226]
Cuando una organización/colectivo se registre:

* El campo `teléfono` **no debería ser obligatorio** (en ese caso las gestiones se harán vía email)

* Una vez enviado el formulario debería redirigir a una página estática con un texto “En breves nos pondremos en contacto contigo para verificar tu cuenta de colectivo… mientras confirma tu email para empezar a participar…” 

**Una vez creada asignarme este issue** para añadir los estilos y textos definitivos :wink:

**Comment by kikito** [comment]
Hola @decabeza,

Como te he dicho por el chat, el teléfono nunca ha sido obligatorio (es posible que el estilo actual diera a entender que sí lo era).

He añadido una "página adicional de instrucciones" para las organizaciones / colectivos. Aparece al registrar un colectivo nuevo. El diseño es inexistente.

Está en la rama `organization-login-226`.

Te asigno esta issue para que le des un diseño tú.

Saludos!

**Comment by decabeza** [comment]
¡Gracias! :+1:

**Comment by decabeza** [comment]
Cerrado por 44ec0cb76dd19725669e0a4ba0698e0e0d99bad9
