### ISSUE TITLE
Añadir filtros a los comentarios

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#227]
Hacer funcional el **filtro para ordenar comentarios** añadido en `/debates/show.html.erb` en la rama **design_filter_comments**

Los comentarios se pueden ordenar por: más nuevos, más polémicos, mejor valorados. 

**Por defecto** deberían estar ordenados por **mejor valorados**. Aunque en el momento de crearlos sigan apareciendo arriba los recién creados como ahora y al recargar la página se ordenan.

Funciona de la misma manera que los filtros de debates (ver #193)

Imagen:

![filter comments](https://cloud.githubusercontent.com/assets/631897/9429164/94137bee-49c7-11e5-99c4-c83537fe9618.png)

**Comment by decabeza** [comment]
Subido nuevos estilos a la rama **design_filter_comments**

Esta parte está comentada en:

* `/debates/_comments.html.erb`

* `/proposals/_comments.html.erb`

No creo que se pueda utilizar el partial `"shared/_order_selector.html.erb"` aquí porque creo que los filtros que aplican son diferentes, además también cambia el HTML.

Imagen del resultado:

![filter_comments](https://cloud.githubusercontent.com/assets/631897/10785919/620169b2-7d67-11e5-9237-7455425a02ef.png)

**Comment by voodoorai2000** [comment]
Closed via #660
