### ISSUE TITLE
Eliminar / paliar N+1 queries

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#228]
Especialmente relevante en:

* Sitios con comentarios (/show)
* Listados extensos (/index)

Listado de tareas:

- [x] Instalar bullet para detectar N+1, missing counters, etc (hecho en #255)

Reducir el número de queries en debates/show y debates index. Candidatos obvios:
- [ ] Renderizar comentarios con una única query (posibles soluciones: [A](http://stackoverflow.com/questions/1372366/how-to-render-all-records-from-a-nested-set-into-a-real-html-tree) y [B](https://gist.github.com/lancejpollard/460814) si utilizamos awesome_nested_set . Quizá podríamos mirar [Ancestry](https://github.com/stefankroes/ancestry) )
- [x] Utilizar una caché para las flags "inapropiadas" - conocemos los ids de los comentarios y debates, así que deberíamos poder cargarlas todas de una vez (hecho en #300)

**Comment by kikito** [comment]
En algunos casos podría mejorarse con caching #219

**Comment by dgilperez** [comment]
[bullet](https://github.com/flyerhzm/bullet) es una gema muy útil para detectar y corregir estas queries.
