### ISSUE TITLE
Añadir buscador de debates

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#231]
Añadido buscador en el sidebar. Está en la rama **add_search**.

**Falta por hacer:**

* Hacer funcional el form del buscador en `/shared/_search_form.html.erb`. 

* Cuando un usuario busque mostrará los debates que contengan el término de búsqueda (en cualquier campo: título, descripción, temas…) con el título “Mostrando N debates que contienen 'búsqueda'” esté título está en `/debates/index.html.erb`

* Los resultados se mostrarán de la misma forma que la actual lista de debates

Imagen del resultado:

![search form](https://cloud.githubusercontent.com/assets/631897/9438439/0458538e-4a5e-11e5-8d2f-2b412b8cc675.png)

**Comment by xuanxu** [comment]
@decabeza al meter el html del formulario dentro del form se ha despinzado ligeramente, ¿le puedes echar un ojo? está ya en master.
