### ISSUE TITLE
Añadir procesos asíncronos

### ISSUE THREAD

**Issue by xuanxu** [AyuntamientoMadrid/participacion#232]
Hay que hacer que algunos procesos, como el envío de emails o sms se hagan de manera asíncrona. 
Para eso tenemos que añadir una librería de trabajos en background como por ejempo [Sidekiq](http://sidekiq.org/)

**Comment by dgilperez** [comment]
:+1: a Sidekiq!

**Comment by xuanxu** [comment]
De momento no tenemos la posibilidad de instalar Redis en los servidores, así que hay que utilizar alguna otra solución que use la base de datos de postgres directamente, por ejemplo [Delayed_job](https://github.com/collectiveidea/delayed_job)
