### ISSUE TITLE
Diseño de "flaggear como inapropiado"

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#233]
Hay dos cosas de diseño por hacer:

- [x] Diseño de las dos pestañas de /moderation (debates y comentarios). Es muy parecido a la de /admin/organizations ( #188 )
- [x] Enlace de "Denunciar / desdenunciar como inapropiado" en debates. Están aquí:

![participacion](https://cloud.githubusercontent.com/assets/63131/9443997/86db671c-4a84-11e5-96a4-b422972371de.png)

**Comment by kikito** [comment]
Nótese que el autor de un comentario / debate no puede flaggear como inapropiado su propio contenido; ha de ser otro usuario.

**Comment by decabeza** [comment]
Añadidos estilos para "flaggear". Subidos a la rama **flag_inappropriate**, quedan por arreglar los test (se ha cambiado "Marcar como revisado" y "Revisados" por "Archivar" y "Archivados") :wink: 

Imágenes del resultado:

![flag_1](https://cloud.githubusercontent.com/assets/631897/9468633/038d5f7c-4b43-11e5-8a6c-8b040c5780ca.png)

![flag_2](https://cloud.githubusercontent.com/assets/631897/9468635/0504504a-4b43-11e5-82be-51bb208d2e5b.png)

![flag_3](https://cloud.githubusercontent.com/assets/631897/9468640/087e65e4-4b43-11e5-99d9-87f78fabafa9.png)

![flag_4](https://cloud.githubusercontent.com/assets/631897/9468641/094f6b80-4b43-11e5-87a9-85f3a01885fb.png)

![moderate comments](https://cloud.githubusercontent.com/assets/631897/9468644/0d1ae032-4b43-11e5-8c8c-49846340b4ab.png)

![moderate debates](https://cloud.githubusercontent.com/assets/631897/9468649/0e94d6fc-4b43-11e5-95a7-7013210e7626.png)

**Comment by kikito** [comment]
Resuelto por #251
