### ISSUE TITLE
Tipos de usuarios en comentarios

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#24]
Mostrar tipo de usuario en los comentarios. (¿Mostrar también en la zona de perfil de usuario?)

Tipos:
- [x] Ciudadano
- [x] Asociación #99 
- [x] Cargo público #100 
- [x] Creador del debate
- [x] Usuario eliminado #103 

![type of user in comments](https://cloud.githubusercontent.com/assets/4169/9134935/385f34f2-3d09-11e5-800e-b622b114afd3.png)

**Comment by decabeza** [comment]
Cerrado por 0b760ff21713e7ee5d50e7b2f1d024abf23d39d7

**Comment by xuanxu** [comment]
:tada:
