### ISSUE TITLE
Votar comentarios

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#25]

**Comment by Ferdy89** [comment]
@voodoorai2000 Asignar la tarea significa que andas trabajando en ella? Si no, puedo echar un cable con esto

**Comment by voodoorai2000** [comment]
Hola @Ferdy89! 

Sí, estoy en ello. Acabamos de actualizar el [Contributing](https://github.com/AyuntamientoMadrid/participacion/blob/master/CONTRIBUTING.md#resolver-una-incidencia) para explicar esto y un par de cosas más.

Cualquiera de estos otros [issues] (https://github.com/AyuntamientoMadrid/participacion/labels/PRs-welcome) están abiertos, coge el que te haga más ilusión!

**Comment by xuanxu** [comment]
Closed by #94
