### ISSUE TITLE
Diseño de "Comentarios ocultos"

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#260]
Los comentarios "visibles" ya tiene un diseño chulo, pero cuando se quedan "ocultos" (tanto en el primer nivel como en los siguientes), la frase "este comentario está oculto" se ve sin estilo y "descolgada del resto".

**Comment by decabeza** [comment]
@kikito he añadido los estilos para los comentarios eliminados en la rama **hidden_comments**. He puesto que solo salgan si `comment.children_count > 0` los eliminados de primer nivel desaparecen directamente.

**Al hacer este cambio hay 3 test que fallan y no sé como solucionarlo** :sob: 

¿Puedes revisarlo please? :pray: 

![deleted comments](https://cloud.githubusercontent.com/assets/631897/9529284/b36469f6-4cf9-11e5-8828-ab41b6a4ce39.png)
