### ISSUE TITLE
Añadir páginas temporales de datos abiertos y transparencia

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#262]
Tenemos que añadir un `/transparencia` y un `/datos_abiertos` con algo de texto (nos darán el texto) apuntando a el sitio web antiguo.

**Comment by decabeza** [comment]
También hacen falta más páginas estáticas (estas no serán temporales) de:

* ¿Cómo funciona?

* Condiciones de uso

* Política de privacidad

**Comment by decabeza** [comment]
Closed by 92940c9f911546e8fa51c3db76c0c69ab80b9025
