### ISSUE TITLE
Cambiar cómo se hacen las extensiones a Paranoia

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#264]
Varios problemas:

* El nombre del fichero debería ser `paranoia_extensions`, no `act_as_paranoid_aliases`
* Tal y como está hecho la única manera de hacer overrides en paranoia es escribir esto:
```
act_as_paranoid ...
include ParanoiaExtensions
```

Lo ideal sería que ParanoiaExtensions se incluyera directamente en el Módulo Paranoia para poder escribir únicamente `act_as_paranoid`, y no tener que acordarnos del nombre.

**Comment by voodoorai2000** [comment]
One of many refactorings.
