### ISSUE TITLE
Optimizar clientes de Savon

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#270]
Ahora mismo creamos los clientes de savon "on the fly". Esto presenta dos problemas:
* Se tiene que obtener el wsdl con una llamada http
* Se tiene que reparsear el wsdl

Para ahorrarnos la llamada http podríamos guardar los wsdls en local. Para no hacer el reparsing podríamos utilizar algún tipo de singleton.

**Comment by dgilperez** [comment]
Podría echarle un vistazo a esto. ¿La dirección del endpoint / WSDL son públicos? ¿Cuales son? Y por otro lado, ¿con qué criterio renovamos el WSDL, manualmente o cada X días?

**Comment by voodoorai2000** [comment]
One of many refactorings.
