### ISSUE TITLE
Hacer más DRY los filtros y selects

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#282]
Empezamos a tener código repetitivo en los selectores de "orden" y en los "filtros":

- [ ] En las vistas que filtran cosas (sobre todo admin y moderate)
- [ ] En los controllers con filtros

Quizá sería el momento de refactorizar ese código duplicado a un par de métodos / partials.

Antes de esto me gustaría que @decabeza le echara un ojo al diseño para ver si podemos simplificarlo y aunarlo todavía más. Por ejemplo: utilizar selects en todos sitios (ahora mismo en los filters se utilizan links)

**Comment by kikito** [comment]
@decabeza : la respuesta que necesito aquí es un "mételo todo en selects" o un "no, deja los filtros en links y los selects donde están" - con eso me puedes pasar la issue de vuelta a mí.

**Comment by decabeza** [comment]
@kikito sorry! efectivamente **deja los filtros en links y los selects donde están** :wink:
