### ISSUE TITLE
Orden

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#301]
Necesitamos añadir un tipo de ordenación parecida a la de reddit en los debates

Fuentes: http://amix.dk/blog/post/19588 / http://www.evanmiller.org/how-not-to-sort-by-average-rating.html http://inaka.net/blog/2015/03/25/hot-score-with-ruby-postgresql-and-elastic-part-1/

**Comment by voodoorai2000** [comment]
Closed via #353
