### ISSUE TITLE
Hacer que los nombres de usuarios no se puedan repetir

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#305]
Ahora cuando un usuario se registra se debería comprobar que ese "Nombre de usuario" no esté ya registrado. 

Se mantiene tal y como está que el usuario pueda cambiar su nombre siempre y cuando el nuevo esté libre.

**Comment by alejanderl** [comment]
Hola,
he visto que el nombre de usuario puede llevar espacios, tildes, etc. Puede estar bien normalizar en un campo username_slug  para hacer la validación contra él y permitir que los usuarios puedan registrarse con username a discreción pero evitando confusiones y falsos duplicados .

De manera que : 
"Ötto Piloto" -> "otto_piloto"
Luego invalidaría: "Otto Pilóto", "otto piloto", ottö_piloto"
