### ISSUE TITLE
Añadir página "Gracias por confirmar tu cuenta"

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#308]
Cuando un usuario recibe un email para confirmar su cuenta y pulsa en el enlace de confirmación se le lleva a la página de login con una alerta de "Gracias por confirmar tu cuenta".

Ahora debería: 

* Hacer autologin.
* Llevar a una página de "Gracias por confirmar tu cuenta" (similar a https://github.com/AyuntamientoMadrid/participacion/blob/master/app/views/organizations/registrations/success.html.erb)

La página de "Gracias por confirmar tu cuenta" tiene este contenido:

¡Felicidades! Ya puedes participar en los debates y enviar propuestas. Si estás empadronado en Madrid, y quieres participar apoyando o votando las propuestas de los demás, necesitamos verificar tu cuenta.
Así nos aseguramos de que cada persona tiene sólo un voto.

"Pulsa aquí para verificar tu cuenta"(verify_path) "o continúa utilizando la página de manera anónima"(root_path)

**Comment by kikito** [comment]
Sobre el auto-login, devise (la gema que utilizamos para autenticar usuarios) antes lo hacía por defecto, pero lo quitaron porque era un agujero de seguridad. Si te equivocas al introducir el email, la persona que tiene ese email no puede hacerse pasar por tí (no conoce el código). Es una posibilidad pequeña, pero es una posibilidad. Así que no lo vamos a hacer, al menos de momento.

Me pongo con el intersticial.

**Comment by xuanxu** [comment]
-1 a hacer autologin
