### ISSUE TITLE
Notificación de "nuevos comentarios en este debate"

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#31]
Una feature bastante usual es que cuando hay "cambios" (en nuestro caso, nuevos comentarios) desde la última vez que se abrió un debate, éste se "distinga visualmente" en el listado de debates de alguna manera.

Depende un poco de cómo de "forero" quieren que sea la herramienta.

@decabeza: ¿qué opinas?

**Comment by decabeza** [comment]
Para esto no sé si tiene sentido el típico "320 comentarios desde tu última visita" o un "22 comentarios (3 nuevos)" o simplemente destacarlo visualmente (negrita, color). ¡Le doy una vuelta! :)

**Comment by voodoorai2000** [comment]
Incluida en #32
