### ISSUE TITLE
Poder cerrar los mensajes de alertas

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#334]
Ahora los mensajes de alertas no se pueden cerrar y es necesario recargar la página para que desaparezcan. A veces tapan partes de la página.

* Hay que añadir una "X" para poder cerrarlas.

* Podrían tener un efecto "fade"/"hide" y que desaparezcan automáticamente en X segundos.

Documentación de Foundation: http://foundation.zurb.com/docs/components/alert_boxes.html

También puede servir de inspiración lo que hace Bootstrap: http://getbootstrap.com/javascript/#alerts-examples

**Comment by voodoorai2000** [comment]
Closed via #381
