### ISSUE TITLE
Error al entrar en la aplicación sin estar logeado

### ISSUE THREAD

**Issue by dbillionlabs** [AyuntamientoMadrid/participacion#351]
Si se intenta entrar en la app sin estar logeado se muestra un mensaje de error.

He visto en otro issue que el diseño de las páginas de error está pendiente, pero creo que en estos casos no se debería mostrar error, sino redireccionar a login y, una vez logeado, llevar a la página de destino.

**Comment by voodoorai2000** [comment]
Muchas gracias @dbillionlabs!
