### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by xuanxu** [AyuntamientoMadrid/participacion#38]
Hay que meter internacionalización y a partir de entonces no incluir más textos sin i18n en el interfaz

**Comment by kikito** [comment]
He investigado esto un poco y esta herramienta nos puede venir bien para hacer la traducción inicial como para "chequear que no metemos más":

https://github.com/balinterdi/i15r

Para el mantenimiento general de los ficheros yml sugiero esta otra:

https://github.com/glebm/i18n-tasks

Con cuidadito también se puede hacer, pero esta gema hace cosas como reordenar las tags alfabéticamente etc.

**Comment by xuanxu** [comment]
added i18n to debates: e9c1910d7d74bc

**Comment by xuanxu** [comment]
Ready.
