### ISSUE TITLE
Error en el certificado con Firefox

### ISSUE THREAD

**Issue by apradillap** [AyuntamientoMadrid/participacion#393]
Hola,

Haciendo una prueba con un compañero de trabajo con Firefox 40.0.3 da un error:
<img width="646" alt="captura de pantalla 2015-09-07 a las 11 11 10" src="https://cloud.githubusercontent.com/assets/69764/9713390/454cc28c-5551-11e5-96e0-68bad64e453d.png">

Parece que falta el certificado intermedio

**Comment by xuanxu** [comment]
Gracias por el aviso @apradillap!, efectivamente hay un error ahí, la gente de sistemas está manos a la obra para subsanarlo.

**Comment by xuanxu** [comment]
esto debería estar ya arreglado

**Comment by apradillap** [comment]
Perfecto!! Ya está corregido sí. Como salía hoy ya en abierto lo probamos y vimos que no mostraba el certificado correctamente, ya está solucionado
