### ISSUE TITLE
Verificación Final redirigir

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#395]
Al verificar tu Padrón y Móvil te lleva a pedir una carta para la confirmación final de tu residencia en Madrid.

Después de darle al botón de enviar carta te enseña el formulario para introducir la clave que has recibido en tu carta por correo, pero aún no has podido recibir esa carta porque no ha dado tiempo.

En lugar de enseñarles el formulario para introducir el código en su carta, deberíamos llevarles a su cuenta o a otra página explicándoles que recibirán una carta con un código.

**Comment by decabeza** [comment]
Creo que lo mejor sería que no llevase a otra página, simplemente que cargue tanto la alerta como el formulario para introducir el código en la misma página, y que siempre que el usuario entre en "Terminar de verificar" le lleve a la misma (adjunto imagen)

![final_verification](https://cloud.githubusercontent.com/assets/631897/9713629/fd4fbd3e-5552-11e5-90b9-1612e1a2563b.jpg)

**Comment by voodoorai2000** [comment]
Closed via #461

**Comment by decabeza** [comment]
Ya está cambiado para que en la misma página muestre la información y el formulario para introducir el código :clap:
