### ISSUE TITLE
Favicon para iphones

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#396]
Estamos viendo una excepción de que no encuentra el apple-touch-icon. 
Seguramente se arregla con esto:
http://stackoverflow.com/questions/28400371/rails-is-showing-me-this-message-every-time-that-i-do-a-request-i-tried-putting

**Comment by decabeza** [comment]
Cerrado por ed0bd904c4f65be9b9845da51c28b0ed98148f1d
