### ISSUE TITLE
CAPTCHA no seguro

### ISSUE THREAD

**Issue by xkill** [AyuntamientoMadrid/participacion#407]
El sistema CAPTCHA implementado se puede saltar facilmente con un OCR (probado con tesseract y gocr y con ambos se puede resolver mas del un 20% de los CAPTCHAS.

¿Por qué no se usa Re-CAPTCHA? Con eso se arreglaria tambien #360

**Comment by xkill** [comment]
¿Por que se cierra? el problema sigue activo

**Comment by voodoorai2000** [comment]
Gracias por el código @xkill tiene pinta de ser peligroso, hay que resolver este tema.
Ya había un issue sobre spam y captchas, seguimos hablando allí https://github.com/AyuntamientoMadrid/participacion/issues/360
