### ISSUE TITLE
Añadir cookie para el popup de IE

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#410]
A los usuarios de IE se les muestra un popup de que la página no está optimizada para su navegador. Está en `/layouts/application.html.erb` para que aparezca el mensaje entren por la url que entren, pero una vez cerrado debería añadir una cookie para no volver a mostrarlo según sigan navegando :wink: 

- [ ] Revisar que sale el popup

**Comment by decabeza** [comment]
Esto está subido en la rama **ie**

**Comment by decabeza** [comment]
El popup está añadido en esta PR (https://github.com/AyuntamientoMadrid/participacion/pull/512) ahora mismo sale en cada página, faltaría por añadir la cookie para que una vez cerrado no aparezca de nuevo. :wink:

**Comment by dgilperez** [comment]
Ahora os mando algo.
