### ISSUE TITLE
Propuestas

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#414]
CRUD
- [x] New
- [x] Show
- [x] Edit
- [x] Index

Validaciones:
- [x] Campos obligatorios del formulario: Título, pregunta, descripción

Notas CRUD:
- [x] Se puede subir un enlace externo. 
- [x] En la descripción se puede poner cualquier link.
- [x] Código de propuesta (MAD-Año-Mes-ID) - aún no está del todo definido.

Permisos
- [x] Todo el mundo puede subir iniciativas
- [x] Las organizaciones pueden crear propuestas, pero no las pueden votar
- [x] Solo pueden votar usuarios verificados
- [x] Hasta 1.000 apoyos se puede editar una propuesta - poner 1.000 como variable en Settings si Yagni lo permite

Relacionadas
- [x] Apoyar
- [x] Texto de haber apoyada una propuesta
- [x] Porcentaje de apoyos
- [x] Añadir resumen de propuestas
- [x] Quitar *featured* proposals
- [x] Añadir índices para las búsquedas
- [x] Añadir campo de video
- [x] Añadir Settings a Pro
- [x] Añadir el campo resumen a las búsquedas
- [x] Mostrar el código de una propuesta
- [x] Home para usuarios logados es Propuestas
- [x] Pones dos botones en Portada, crear debate y crear propuesta 
- [x] Comentar
- [x] Votar comentarios
- [x] Reportar
- [x] Ordenar
- [x] Buscar
- [x] Cachear
- [x] Crear una portada con los 10 debates y 10 iniciativas mejor valoradas
- [x] Administrar propuestas
- [x] Moderar propuestas
- [x] Añadir texto explicativo del funcionamiento de Propuestas a la página de more_information
- [x] Pedir nombre y apellidos para crear una propuesta

Deploy:
- [ ] Ejecutar *rake debates:hot_score*

**Comment by xuanxu** [comment]
:tada:
