### ISSUE TITLE
Compartir en redes sociales

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#416]
Hay un par de detalles que pulir:

- [ ] 'via' no funciona correctamente para twitter, con este fork parece que va bien https://github.com/cuterxy/social-share-button
- [x] Para que Facebook y Google+ cargue bien el título de la página, debemos cambiar la etiqueta html 'title' de las páginas de debates al nombre de los debates en sí.

**Comment by jonarribasmateo** [comment]
+1 los 'titles' no funcionaba bien
<img width="483" alt="captura de pantalla 2015-09-07 a las 21 31 15" src="https://cloud.githubusercontent.com/assets/4953393/9722123/e4a57184-55a7-11e5-9872-b5787ae44c75.png">

**Comment by voodoorai2000** [comment]
Has been fixed
