### ISSUE TITLE
Las etiquetas sugeridas no deberían mostrarse y que se puedan pinchar, sino que se deberían autocompletar a medida que el usuario las vaya escribiendo

### ISSUE THREAD

**Issue by juanramb** [AyuntamientoMadrid/participacion#417]
Hay gente que lo que hace es pinchar en todas las etiquetas, con lo que se pierde el valor de filtrado de éstas

**Comment by decabeza** [comment]
Cierro ya que hemos abierto #541 para limitar el número de etiquetas que pueden usarse y evitar así el problema que nos comentas :wink:
