### ISSUE TITLE
Búsquedas con y sin acento

### ISSUE THREAD

**Issue by jonarribasmateo** [AyuntamientoMadrid/participacion#418]
Debería poder buscarse con y sin acento (por ejemplo 'Tetuan' por 'Tetuán')
<img width="1440" alt="captura de pantalla 2015-09-07 a las 21 36 32" src="https://cloud.githubusercontent.com/assets/4953393/9722168/8ee60b90-55a8-11e5-8ac3-67c28ab8e8a9.png">
<img width="1439" alt="captura de pantalla 2015-09-07 a las 21 36 24" src="https://cloud.githubusercontent.com/assets/4953393/9722169/8f04da5c-55a8-11e5-84b9-a2adc1ae1c4e.png">

**Comment by dgilperez** [comment]
@voodoorai2000 cambiamos [`Debate.search`](https://github.com/AyuntamientoMadrid/participacion/blob/master/app/models/debate.rb#L140) por [`pg_search`](https://github.com/Casecommons/pg_search), más robusto que usar SQL? Tiene la pega de que sólo sirve para *Postgresql*, pero realmente no creo que sea un problema ahora. Puedo enviar un PR si os parece OK.

**Comment by voodoorai2000** [comment]
No tengo una preferencia importante.
Si es sólo por los acentos igual iría a por una migración con `CREATE EXTENSION unaccent;`.
Si vamos a necesitar más temas de full text search igual si que me lanzaría con pg_search, pero de momento no veo la necesidad.

**Comment by voodoorai2000** [comment]
No tenemos permiso para ejecutar Extensiones de Postgres. Seguramente el lunes ya los tendremos. Vuelve a abrir el Issue temporalmente para que no se nos olvide meter los cambios. https://github.com/AyuntamientoMadrid/participacion/commit/58a780bac5554a70de8d2624e57e91105627f745

**Comment by voodoorai2000** [comment]
Closed via #654
