### ISSUE TITLE
Titles de las páginas debería ser título del debate

### ISSUE THREAD

**Issue by jonarribasmateo** [AyuntamientoMadrid/participacion#419]
Por SEO y por todo.
<img width="1440" alt="captura de pantalla 2015-09-07 a las 21 54 05" src="https://cloud.githubusercontent.com/assets/4953393/9722302/0a4536e2-55ab-11e5-8e95-69165ab6c796.png">

**Comment by decabeza** [comment]
¡Gracias! Cierro este issue ya que está duplicado. Es una parte de #416 :wink:
