### ISSUE TITLE
Añadir enlaces en debates y comentarios

### ISSUE THREAD

**Issue by Poliuk** [AyuntamientoMadrid/participacion#421]
No se puede enlazar a otros debates ni a otras webs desde los comentarios:

![screen shot 2015-09-08 at 01 13 16](https://cloud.githubusercontent.com/assets/2798729/9723674/e33eb048-55c6-11e5-848e-6fd654e71820.png)

Tampoco tengo un enlace directo al comentario.

**Comment by decabeza** [comment]
Se deben poder poner enlaces:

* En el contenido del propio debate.

* En los comentarios.

**Comment by dgilperez** [comment]
¿A cualquier dominio o sólo a decide.madrid.es? ¿Qué os parece usar [auto_html](https://github.com/dejan/auto_html)?

**Comment by xuanxu** [comment]
en vez de auto_html, a mi me mola más [rinku](https://github.com/vmg/rinku)

**Comment by dgilperez** [comment]
@xuanxu entonces harías el autolinking en tiempo de carga y no guardarías el body procesado y con los enlaces sustituidos en DB? O rinku + un campo `body_html` en el modelo para almacenar el texto procesado?

**Comment by xuanxu** [comment]
bueno, se podría pasar rinku antes de guardar en BD también, habría que ver en cada caso, es diferente para los comentarios (un textarea simple) que para el debate (que usa el CKEditor y hay posibilidad de editar). Si guardamos el html con los enlaces preprocesados, luego eso hay que hacerlo html_safe así que habría que sanitizar antes también. 

Así intuitivamente me parece que rinku para los comentarios en el momento de mostrarlos no sería mucha carga porque en general van a estar cacheados. Y para los debates igual bastaría con activar la opción de links en el CKEditor. Pero lo digo un poco a la ligera sin mirar el código ahora mismo.

Igual hay que pensar cada uno de los dos casos por separado y partir este issue en dos ¿cómo lo veis @voodoorai2000, @kikito?

**Comment by dgilperez** [comment]
Ya veo. La parte de CKEditor (debates) no la tengo clara, no lo controlo bien y prefiero que lo mire otro. Con los comentarios, estoy de acuerdo con lo que dices, van a estar cacheados casi siempre con lo que creo que es mejor no complicar el schema. Hay PR (#462) para eso, seguimos ahí.

**Comment by decabeza** [comment]
Ya está subido a producción :clap:
