### ISSUE TITLE
Los comentarios de debates ocultos no deben aparecer en el interfaz de moderación

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#423]
Si el debate está oculto, sus comentarios no deberían aparecer en la interfaz de moderación

**Comment by xuanxu** [comment]
Esto ya es así, solo aparecen los que se hayan ocultado previamente (y que por tanto se pueden desocultar para que aparezcan solo en caso de que el debate se desoculte).

La PR #518 cubre los casos que faltaban.
