### ISSUE TITLE
Añadir campo en el form de registro de organizaciones

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#434]
Hay que añadir un campo en el form de registro de organizaciones de "Nombre del responsable" con la nota "Persona responsable de presentar la propuesta".

**Comment by xuanxu** [comment]
El campo es "nombre y apellidos de persona responsable del colectivo" (con una aclaración tipo "será la persona representante de la asociación/colectivo en cuyo nombre se presenten las propuestas")
