### ISSUE TITLE
Colapsar comentarios

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#438]
Hay que añadir la posibilidad de que **todos los comentarios con hijos se puedan colapsar **(independientemente del nivel al que estén).

Algo así:

![collapse_comments](https://cloud.githubusercontent.com/assets/631897/9755821/85c3acec-56d5-11e5-8578-4e5245a2f010.jpg)

**Comment by voodoorai2000** [comment]
Obsolete
