### ISSUE TITLE
Emails sobre comentarios

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#449]
- [ ] Problema1:
  Si marcas que quieres recibir emails sobre comentarios en tu debate en 'Mi cuenta' y escribes en tu propio debate recibes un email. No deberíamos mandar emails sobre tus propios comentarios en tu debate

- [ ] Problema2:
  Si marcas que quieres recibir emails sobre respuestas a tus comentarios en 'Mi cuenta' y respondes a tu propio comentario, recibes un email. No deberíamos mandar emails sobre tus propias respuestas a tus comentarios.

**Comment by dgilperez** [comment]
Me lo cojo.
