### ISSUE TITLE
Número de comentarios en un debate

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#452]
Al ocultar un comentario, debería disminuir el número total de comentarios de un debate. Ahora mismo se mantiene igual.

**Comment by xuanxu** [comment]
Si se oculta un comentario individualmente sí se actualiza el contador de su debate, el error sucede cuando se ocultan en bloque al banear a un usuario.

Por otro lado no estaban actualizandose los contadores al hacer restore ni individualmente ni en bloque. El caso de restore individual lo arregla la PR #477 

Para los casos de eliminar/restore en grupo, que son los que faltan ahora, hay que cambiar [estos métodos](https://github.com/AyuntamientoMadrid/participacion/blob/master/lib/acts_as_paranoid_aliases.rb#L49-L57) intentando mantenerlos eficientes.
