### ISSUE TITLE
Filtrar por etiquetas

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#455]
Problema:
  Al filtrar por algunas etiquetas no aparecen los debates etiquetados.

Por ejemplo:
  El debate [312](https://decide.madrid.es/debates/312) está etiquetado con 'Latina'.
  Pero al hacer click en la [etiqueta](https://decide.madrid.es/debates?tag=Latina) no aparecen resultados.

Sugerencias:
  Parece que tiene algo que ver con como `Debate.tagged_with(name)` trata las mayúsculas de una etiqueta.

**Comment by voodoorai2000** [comment]
El problema parece seguir ahí, vuelvo a abrir este issue.

**Comment by nogates** [comment]
Hola @voodoorai2000 

He intentado reproducir esto localmente y no he podido. Los debates salen listados por la etiqueta sin importar minúsculas o mayúsculas y la consulta SQL parece que pone todo en mínuscula antes de hacer la comparación....

Yo creo que miraría la base de datos, y comprobaría que no hay más de una étiqueta con ese nombre :question:

**Comment by xuanxu** [comment]
Con el nuevo buscador que hemos subido recentemente esto ya no pasa. Cierro el issue.

**Comment by xuanxu** [comment]
Reabro. Este issue se refiere al filtro por etiqueta, no a los resultados del buscador que ya son correctos.

**Comment by xuanxu** [comment]
Caso resuelto: 
En producción había dos etiquetas "Latina" y "LATINA", de antes de que unificaramos a minúscula. Y cuando hay más de una etiqueta cuyo lower es igual [ActsAsTaggableOn devuelve cero resultados](https://github.com/mbleigh/acts-as-taggable-on/blob/master/lib/acts_as_taggable_on/taggable/core.rb#L172-L174).

Hemos corregido el problema en producción migrando los elmentos etiquetados con "LATINA" a la etiqueta "Latina"
````ruby
upcase_latina.each do |tagging|
  tagging.tag_id = downcase_latina.id
  tagging.save
end
upcase_latina.destroy

````
