### ISSUE TITLE
Unir hilos de propuestas similares

### ISSUE THREAD

**Issue by rosa2** [AyuntamientoMadrid/participacion#474]
Hola

En [¿Qué os parece este nuevo espacio de debate?](https://decide.madrid.es/debates/3) continuan habiendo propuestas interesantes para mejorar la herramienta. Una que se ha reportado mucho es la posibilidad de unir hilos con temas similares. Hacerlos comentarios de una que inicie o resuma bien el tema. También se le tendrían que añadir los votos de las propuestas similares y comprobar antes de añadir que un usuario no ha votado ya.

Espero que os sirva

**Comment by xuanxu** [comment]
esa funcionalidad la tenemos en mente, intentaremos ponerla en funcionamiento una vez acabemos con las tareas más prioritarias.
