### ISSUE TITLE
Privacidad del voto respecto al DNI

### ISSUE THREAD

**Issue by rosa2** [AyuntamientoMadrid/participacion#475]
La seguridad del usuario respecto a su voto creo que ha de ser tan importante como en la calle o en su casa. Tan anónima como cuando se vota en las elecciones. Tanto DNIs como su relación con los votos pueden ser interesantes para el cibercrimen y para partidos/polítcos/funcionarios corruptos que pueden incluso acabar con represalias políticas.

Por eso propongo que cuando se apruebe o rechace una propuesta en el ayuntamiento se desligue el DNI de ese voto.  Quizás esto lo tendría que proponer en (http://decide.madrid.es) ...

Buenas noches

**Comment by rosa2** [comment]
De https://decide.madrid.es/debates/3 del usuario Future for Madrid  

*6: Seguridad: Dada la versión tan temprana del sistema (v.0.9) ¿Existen las medidas para garantizar la integridad del sistema?, los desarrolladores tienen experiencia en desarrollos de internet seguros, hay detector de intrusos, sistema de monitorización 24h, etc.. Manejáis datos y opiniones escritas por los madrileños, accesos indebidos con robos de información pueden destapar a los usuarios y desencadenar denuncias por irresponsabilidad de la custodia de la información. *

**Comment by xuanxu** [comment]
Gracias @rosa2 por tus comentarios, ahora mismo desligar el dni de los votos es imposible porque el dni es lo que nos garantiza que los votos son únicos por persona, si desligaramos el DNI un mismo ciudadano podría votar múltiples veces. De todas maneras lo de esta web no son exactamente 'votos' sino más bien 'apoyos'. Si una propuesta consigue suficientes apoyos será llevada a Consulta o Referendum donde sí se podrá votar sin que el voto quede asociado al DNI. En ese aspecto la acción que puedes realizar en la web es más parecida a la que haces cuando apoyas una campaña de recogida de firmas, donde para que sean válidas también hay que proporcionar el DNI.

En cuanto a la seguridad y la integridad del sistema, te podemos asegurar que la seguridad es muy alta y se tiene muy en cuenta, se toman las mismas medidas que con cualquier otra base de datos importante que maneja el ayuntamiento (padrón, impuestos, etc...) y se almacenan los mínimos datos necesarios.
