### ISSUE TITLE
Problemas detectados de accesibilidad

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#481]
Los de sitevalidator nos han hecho graciosamente un análisis automatizado de problemas de accesibilidad:

https://t.co/fwgZXkeKhU

**Comment by dgilperez** [comment]
El problema más repetido (https://app.sitevalidator.com/s/ab07b45362c92dc3b8564794/i/7456472), el de las los atributos `alt` perdidos, queda resuelto (creo que del todo) con el PR que acabo de enviar.

**Comment by decabeza** [comment]
Cierro por que la gran mayoría de pequeños errores de accesibilidad están arreglados y vamos a solicitar un nuevo informe de accesibilidad con el que crearemos un nuevo issue con los errores concretos que sea necesario arreglar :+1:
