### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#49]
Hace falta que metamos algún sistema para hacer "lo que hace google analytics pero sin hacer google analytics".

El objetivo es poder tener métricas tipo: dónde entra la gente y dónde no, cuántos accesos por móvil hay, etc. Para poder hacer tests tipo "hemos perdido usuarios con este cambio"

Opciones:
* Lo que tenga el IAM (si tiene algo)
* Algo open-source (yo he usado [piwik](http://piwik.org) )
* Montar algo nosotros desde cero (poco probable que podamos llegar al nivel de piwik o similiares a no ser que ya haya algo para rails hecho)

Idealmente hay que dejar la puerta abierta para que el resto de organismos que lo utilicen puedan usar otra cosa (como google analytics)

**Comment by javierhonduco** [comment]
https://github.com/ankane/ahoy :smile:

**Comment by kikito** [comment]
@javierhonduco  :+1:

**Comment by voodoorai2000** [comment]
+1 ahoy

**Comment by eloy** [comment]
Hola! Alguien con esto?? Si no hay nadie puedo empezar añadiendo ahoy..

**Comment by kikito** [comment]
Buenos días @eloy. No hay nadie de momento con esto, empieza cuando quieras, y gracias!

**Comment by GermanDZ** [comment]
Con Ahoy se registra muy bien. Ya para explotar los datos es otra cosa con @amuino algo hemos hecho pero poco.

**Comment by eloy** [comment]
Totalmente de acuerdo @GermanDZ, hacer un dashboard decente va a necesitar trabajo, pero a la hora de añadir datos es una caña!

**Comment by eloy** [comment]
He añadido un PR que añade las gemas y migraciones, configura alguna opción de ahoy, añade algún evento de prueba y muestra gráficas de forma bastante rudimentaria. Mucho cuidado porque no he implementado nada de autenticación, por lo que si eres usuario puedes verlas. 

Como storage he configurado Postgres JSONB. El único requisito es que la version de la base de datos sea 9.4, supongo que no sera un problema, pero se puede cambiar si lo fuera. Esta configuración es perfecta para desarrollo, pero en producción sería buena idea usar un storage independiente de la base de datos principal. 

El dashboard es algo rápido y sencillo. Una vez tengáis claro que librería se va a usar para el frontend y que datos se van a recoger se puede hacer algo mucho mas chulo.

**Comment by voodoorai2000** [comment]
¡Muchas gracias @eloy! 

Esto va a venir de perlas :ok_hand: 

No hay problema en utilizar Postgres 9.4, pero por favor actualiza el README para reflejarlo.

Las librerías de Google están vetadas en este proyecto. Necesitaríamos utilizar otra librería para pintar los gráficos.

**Comment by amuino** [comment]
Para gráficos, lo último que he probado y con lo que estoy muy contento es c3.js: http://c3js.org (por si no tenéis opciones suficientes en la cabeza :-) )

**Comment by voodoorai2000** [comment]
Gracias por las recomendación @amuino :-) 

c3.js iría perfecto!

**Comment by eloy** [comment]
Sin problema @voodoorai2000, hago los cambios y actualizo el PR. 

Gracias por la recomendación @amuino! La verdad que siempre que he tenido que hacer algo de gráficas he ido perdido.. Probare esa a ver que tal :)

**Comment by dgilperez** [comment]
Por añadir otra opción al tema de los gráficos: he probado recientemente los [metrics-graphics](http://metricsgraphicsjs.org/) de Mozilla y me parecen de lo mejorcito que hay por ahí, tanto que hasta monté una gema para integrarlo con el pipeline de Rails, helper incluido: [metrics-graphics-rails](https://github.com/dgilperez/metrics-graphics-rails). Quizás no tan completos en features como otras opciones, pero también quizás eso es bueno :smile: 

PD: Enhorabuena por esta iniciativa que acabo de conocer, contribuiré algo si me dejáis :)

**Comment by eloy** [comment]
Hola @voodoorai2000!

He actualizado el pr con cambios para mostrar las gráficas usando c3.js en lugar de charkick, que depende de librerías de google u otras no libres. He añadido una clase para ayudar a generar los datos.. Su utilidad dependerá del tipo de datos que se quieran mostrar así como la fuente, pero por lo menos para empezar servirá. 

Pegarle un vistazo y cualquier cambio adicional que necesite me cuentas.

**Comment by voodoorai2000** [comment]
Hola @eloy!

Muchas gracias!

Tiene buena pinta, si arreglas los conflictos te la mergeo!

**Comment by xuanxu** [comment]
Hay un buen puñado de conflictos relacionados con funcionalidad nueva, si quieres arreglo el merge yo.

**Comment by voodoorai2000** [comment]
:+1:

**Comment by xuanxu** [comment]
Mergeado! :tada:
