### ISSUE TITLE
Validación DNI

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#498]
- [ ] Mayúsculas (implementado, pero comprobar)
- [ ] Mayores de 16 años (implementado, pero falta un test)
- [ ] Cualquier caracter que no sea un número o una letra
- [ ] Posibles ceros al principio y al final del DNI

**Comment by dgilperez** [comment]
En otros proyectos he usado este validador con éxito: https://github.com/javiertoledo/spanish_vat_validators
