### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#50]
Básicamente un highlight es un "Banner" que aparece en algunas views. Lo configura el administrador.

Un highlight pueden ser varias cosas:

* Una Iniciativa (Aparece su foto si la tiene, texto y si haces click en ella te lleva a la iniciativa)
* Un enlace externo con un link (por ejemplo a una noticia relacionada con la democracia participativa)

Sugerencia: hacer que siempre sea un combinado link+texto+imagen, y luego permitir a los administradores "crear destacado de esta iniciativa" y que les rellene el texto (así lo pueden cambiar)

**Comment by eloy** [comment]
Hey,  Si nadie ha empezado con esto puedo echar una mano..

**Comment by voodoorai2000** [comment]
Hola @eloy!

Genial, dale! 

Cualquier duda aquí estamos :)

**Comment by voodoorai2000** [comment]
@eloy hemos estado hablando un poco sobre este issue y tengo que advertirte que está muy verde y pueden haber cambios importantes.
El tema de Iniciativas viene después del de Debates y aún no tenemos claro si este issue se tendría que implementar antes de poner la aplicación online.

Si te llama otro issue que esté más definido, sería genial.

Si aún así quieres trabajar en esto, lo único que tenemos claro es que hará falta una zona admin para la que teníamos pensado utilizar ActiveAdmin. Abro otro issue sobre esto.

**Comment by eloy** [comment]
Sin problema @voodoorai2000, estaba a punto de decírtelo porque no he visto nada de admin en el código.
Busco otra cosa que este mas clara.

**Comment by voodoorai2000** [comment]
:+1:
