### ISSUE TITLE
Problemas mostrando votacion en index

### ISSUE THREAD

**Issue by alejanderl** [AyuntamientoMadrid/participacion#508]
Estoy casi seguro de no haber votado a este debate, y sin embargo me aparece como votado.
username 'janderl'
![screen shot 2015-09-15 at 21 55 29](https://cloud.githubusercontent.com/assets/1504445/9888361/f3ade44c-5bf4-11e5-8c2e-c503bca0f871.png)
He hecho la prueba con otro:
![img_20150915_215328631](https://cloud.githubusercontent.com/assets/1504445/9888633/7bb714c0-5bf6-11e5-89ab-77d9d1937009.jpg)
Y después de votar no:
![img_20150915_215338892](https://cloud.githubusercontent.com/assets/1504445/9888657/8ca74e9e-5bf6-11e5-9dae-0d8949059c63.jpg)

**Comment by decabeza** [comment]
Hola @alejanderl, ¿te ha vuelto a ocurrir?

He estado haciendo pruebas (con Chrome) votando, cambiando el voto y refrescando la página y no he tenido problema. 

Si te ha vuelto a pasar me dices y veo como reproducir el error :wink:
