### ISSUE TITLE
Reemplazar Google Captcha por "Algo que no sea de Google"

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#51]
"No podemos hacer que cada vez que alguien entra en un proceso participativo Google lo sepa".

Observaciones: Existe la posibilidad de preguntar al IAM cómo lo hacen ellos. Pero sus páginas usan JSP así que probablemente sea algo java-centric.

Sugerencia: https://github.com/pludoni/simple-captcha

**Comment by dvelayos** [comment]
alternativas: https://www.ruby-toolbox.com/categories/rails_captcha
