### ISSUE TITLE
validación con dni/certificado digital

### ISSUE THREAD

**Issue by jaimess** [AyuntamientoMadrid/participacion#516]
La verificación de identidad debería ser también (opcionalmente) con dni/certificado digital

**Comment by decabeza** [comment]
Hola @jaimess, gracias por la idea, pero al principio del proyecto se descartó la utilización del DNI/certificado digital por el bajo uso que tiene entre los ciudadanos en sus gestiones con la Administración pública.

**Comment by jaimess** [comment]
Me gustaría saber la estadística que habéis usado, porque me gustaría
pensar que os habéis basado en datos y no en percepciones personales.
En cualquier caso, es un desarrollo que lleva entre una y dos jornadas de
trabajo, (según la experiencia del desarrollador), si cada gestión del
funcionario para hacer la validación + envío de carta con la clave o
recogida del ciudadano en la oficina lleva al menos quince minutos, con que
hubiera 64 ciudadanos que usasen el dni o certificado válido, amortizarían
el desarrollo, (por no hablar de que se reutilizaría en otros proyectos).
En el caso más pesimista, en serio, ¿no va a haber 100 ciudadanos que lo
usen?
Siendo sincero, me da igual que se pueda usar certificado o no, al final
podré votar, pero me molesta ver que pudiendo hacer las cosas de forma
eficiente no se hagan.
