### ISSUE TITLE
Política de cookies EU

### ISSUE THREAD

**Issue by dgilperez** [AyuntamientoMadrid/participacion#523]
La EU obliga a todas las webs que almacenen cookies a explicar cuáles y por qué, y a pedir el consentimiento del usuario. No hacerlo puede causar un problema con la Agencia Española de Protección de Datos.

He resuelto este requisito usando [esta gema](https://github.com/infinum/cookies_eu) en otros proyectos, que tiene defaults en varios idiomas incluido español. Si queréis os puedo mandar un PR. Aparte de eso, sería necesario generar el texto legal, ahí puedo proponer una plantilla pero os puedo ayudar menos.

**Comment by xuanxu** [comment]
Queremos evitar en esta web cualquier intromisión al usuario, por eso de momento vamos a no meter el aviso sobre uso de cookies. Por un lado [la ley](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2) exime a cierto tipo de cookies básicas, y por otro no estamos utilizando ninguna cookie de terceros ni guardando información que no sea imprescindible para mantener una sesión de un usuario logado. Así que pensamos que estamos cubierto y podemos no mostrar el aviso. Si llega una denuncia en caso contrario ya veremos :)

**Comment by dgilperez** [comment]
Perfecto entonces, gracias por la aclaración!
