### ISSUE TITLE
Añadir etiquetas meta para soportar Twitter Cards

### ISSUE THREAD

**Issue by Almorca** [AyuntamientoMadrid/participacion#526]
Las Twitter Cards ( https://dev.twitter.com/cards/overview ) son una serie de etiquetas que permiten mostrar información extendida de una página si esta es enlazada desde Twitter lo que redundaría en una mejor visualización de las propuestas cuando se enlacen desde twitt.

La implementación es sencilla ya que sólo habría que añadir 4 ó 5 etiquetas meta a las páginas de propuestas.

**Comment by xuanxu** [comment]
Hecho y subido a producción!
