### ISSUE TITLE
Cambios en la interfaz de moderación

### ISSUE THREAD

**Issue by xuanxu** [AyuntamientoMadrid/participacion#530]
Hay que replicar el funcionamiento del interfaz de moderación de propuestas para los debates y los comentarios:

- [ ] Han de tener tres filtros: (Pendientes, Todos, Marcados como revisados), y excepto el filtro 'Todos' los otros **sólo muestras objetos denunciados**.
- [ ] Se pueden ordenar por created_at y flagged.
- [ ] El filtro y orden por defecto es Pending, ordenado por flags.
- [ ] Con esto se elimina el apartado de moderar en bloque del menu de moderación, porque la moderación en bloque se hace en el filtro "Todos" de cada elemento (debates, comentarios)

En propuestas está ya todo funcionando así una vez que se haga merge de la PR #529 Falta dejar igual moderation/Debates y moderation/Comments

**Comment by decabeza** [comment]
Además dela lista anterior hay que:

- [ ] Mostrar el **texto completo en `/admin/proposals`** no sólo el título.

- [ ] Mostrar el **texto completo en `/admin/debates`** no sólo el título.

- [ ] Mostrar el **ID del admin/moderador** que haya ocultado el debate en `/admin/debates`, la propuesta en `/admin/proposals`, el comentario en `/admin/comments` y el usuario en `/admin/users`
