### ISSUE TITLE
Mostrar mensaje al verificar el padrón   

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#533]
Cuando un usuario intente verificar su residencia, si introduce un código postal de Madrid (comunidad) diferente al código de postal de Madrid (municipio) hay que mostrarle un mensaje diferente al de error actual, algo como "Por favor, para verificarte debes estar empadronado en el municipio de Madrid."

**Mensaje actual:**
![screen shot 2015-09-19 at 13 36 37](https://cloud.githubusercontent.com/assets/631897/9976019/a1c99de2-5ed3-11e5-8d17-586d17b2aaa8.png)

**Mensaje nuevo (para no empadronados en Madrid):**

![screen shot 2015-09-19 at 13 37 36](https://cloud.githubusercontent.com/assets/631897/9976021/ad2e48c2-5ed3-11e5-817a-4f2dd4d34413.png)

**Comment by xuanxu** [comment]
¿Tenemos una lista de todos los códigos postales de Madrid municipio? ¿o la regla es que son de Madrid si y solo si 280XX?
