### ISSUE TITLE
Conectarse con Ciudadano360 para hacer login de usuarios

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#55]
Primer email mandado al responsable de Ciudadano360

> Buenas,
> [...]
> Uno de los retos a los que nos enfrentamos es: queremos que el login entre las dos webs sea lo más transparente posible; que cuando alguien tenga una cuenta en la página de democracia participativa pueda entrar con sus datos de Ciudadano 360, y viceversa.

> Esto es un primer email para ir abriendo el camino y barajando opciones. Te explico cómo lo veo yo:

> Para hacer la primera parte, necesitaríamos un endpoint de Ciudadano360 al que poder decir "este usuario y passwords (o esta cuenta de Google o Facebook), son correctos? Si sí, qué nivel de seguridad tienen?". Con una respuesta positiva, podríamos crear una cuenta en la web y marcarla como "autenticada".

> Para hacer la segunda parte (el "viceversa") necesitaríamos que la web de participación ciudadana pudiera crear usuarios en Ciudadano360. Haría falta un endpoint tipo "Crea este usuario nuevo con este login+password/facebook/google").

> No tienen por qué ser dos endpoints distintos: podría ser uno único en plan "crea o valida este usuario en Ciudadano360, y devuélveme su nivel".

> Como es una petición muy concreta me imagino que no tendréis algo así ya hecho. De todas formas esto es la idea que yo tengo, sin saber cómo funciona Ciudadano360. A lo mejor hay alguna otra cosa que ya tengáis que podamos utilizar (por ejemplo, si Ciudadano360 ya tiene un servicio existente de importación/exportación de usuarios)

> [...]

**Comment by kikito** [comment]
- [x] Enviar formulario con petición de acceso a nuestra app

**Comment by Pi-Po** [comment]
La idea no es mala. Pero ahora me vuelve la pregunta respecto a la Eliminación de un Usuario.

Sugerencia:

Que exista alguna posibilidad para que el Usuario pueda eliminarse de la Herramienta de Votación Ciudadana y no de su Usuario con Ciudadano360. 
Que exista alguna posibilidad para que el Usuario pueda eliminarse de Ciudadano360 y no de su Usuario con la Herramienta de Votación Ciudadana. 
Que exista alguna posibilidad para que el Usuario pueda decidir su "Olvido Definitivo" eliminando simultaneamente su Usuario en Ciudadano360 y en la Herramienta de Votación Ciudadana.
Que en el registro del Usuario en Ciudadano360 o en la Herramienta de Votación Ciudadana, se le dé la posibilidad de que acceda a ambas con su mismo Usuario.

**Comment by voodoorai2000** [comment]
Obsolete
