### ISSUE TITLE
Managers

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#573]
- [x] Los managers tienen login + salted password 
- Los managers tienen su propia pantalla de index (`/management`) con:
  - [x] Crear y verificar usuarios
  - [x] Crear Propuestas
  - [x] Apoyar propuestas
- [x] Los managers hacen login mediante UWEB.
- [x] Guardar en sesión el usuario al que se está asistiendo.
- [x] Cerrar la sesión cuando se haya terminado de asistir a un usuario.
- [x] Al crear una propuesta redirigir a la vista individual dentro de management.
- [x] Mostrar al usuario siendo asistido en las vistas para crear y mostrar una propuesta individual (layout?)
- [x] Mostrar las opciones en el menu para crear, apoyar e imprimir propuestas.
- [x] Los managers deberían poder acceder sólo a la sección de managers, no al resto de la web.
- [x] Al verificar por email el usuario debería ser de nivel dos
- [ ]  Los managers no deberían tener acceso a la vista de mi cuenta de un usuario (marcado con CHANGE ME en el código)
- [x] Diferenciar el mensaje de cerrar sesión entre managers y usuarios asistidos
- [x] Comprobar que siempre hay un usuario siendo asistido (excepto al imprimir) (sugerencia utilizar un before_action)
- [ ] Al hacer click en una propuesta debería mostrarse la propuestas dentro del layout management.
- [x] Añadir enlace a imprimir propuesta individual

Tests:
  - [ ] Arreglar tests para identificarse y salir para managers y el usuario siendo asistido
  - [ ] Testear el método managed_user
  - [ ] Testear la información mostrada de la cuenta del usuario siendo asistido
    - [ ] Si el usuario está verficado mostrarlo
    - [ ] Sino mostrar sólo el tipo y número de documento
    - [ ] Si no hay un usuario siendo asistido no mostrar la información de su cuenta

Estilos:
 - [x] Añadir el icono para imprimir en el menu.
 - [x] Crear un print.css para imprimir las propuestas.
 - [x] Información del usuario siendo asistido.
 -  [x] Colocar botón para imprimir en 'Imprimir propuestas'

Pruebas en Pre:
  - [x] Crear 100 usuarios de prueba de nivel 1 y 2
  - [x] Quitar concepto de beta testers

Feedback sugerido desde UWeb:
  - [x] Verificar DNI de 16 años
  - [x] Permitir Letra minuscula en DNI
  - [x] En la sección de imprimir mostrar las más apoyadas por defecto
  - [x] Añadir botón de imprimir en las políticas de privacidad
  - [x] Añadir botón de imprimir el formulario relleanado antes de crear propuesta
  - [x] Añadir botón de imprimir al show de una propuesta recién creada

**Comment by decabeza** [comment]
Imágenes del flow de "Usuarios":

![usuarios_2909_1](https://cloud.githubusercontent.com/assets/631897/10170908/8d94f0c2-66d7-11e5-9a4d-ff3054ebbcef.jpg)

![usuarios_2909_2](https://cloud.githubusercontent.com/assets/631897/10170907/8d94142c-66d7-11e5-842f-84b3bb9113c4.jpg)

![usuarios_2909_3](https://cloud.githubusercontent.com/assets/631897/10170905/8d90c8f8-66d7-11e5-8ba5-9e01bdca6a89.jpg)

![usuarios_2909_4](https://cloud.githubusercontent.com/assets/631897/10170909/8d99ee24-66d7-11e5-9052-1065c973f85c.jpg)

![usuarios_2909_5](https://cloud.githubusercontent.com/assets/631897/10170906/8d932b0c-66d7-11e5-8801-51ffb38c15b2.jpg)

![usuarios_2909_6](https://cloud.githubusercontent.com/assets/631897/10170904/8d8cea9e-66d7-11e5-84e0-07724d406c4a.jpg)
