### ISSUE TITLE
Actualizar readme

### ISSUE THREAD

**Issue by piranna** [AyuntamientoMadrid/participacion#58]
Actualizar el readme del proyecto indicando de que va, en vez de usar el generico de Ruby

**Comment by piranna** [comment]
Gracias. Seria recomendable que por cuestiones de calidad y mantenibilidad, tanto el codigo como la documentacion (incluido el readme) como los issues esten en ingles. He abierto el issue en español por homogeneidad, pero no es lo correcto en el desarrollo de software.

**Comment by kikito** [comment]
Hola Piranna,

El tema de qué partes hacer en inglés y cuales en español es complicado y tiene varias capas y varios puntos de vista.

Lo primero que hay que decir es que el proye

Lo primero es decir que el código en sí está entero en inglés (si hay algo en español, es por error, no por diseño - feel free to open an issue). Ahí no hay discusión.

El tema del Readme y las issues es un poco más complejo.

Lo primero que hay que saber es que hay varias fases planificadas. La primera fase es una aplicación que se utilizará únicamente en el Ayuntamiento de Madrid. Más adelante la idea es dejarla convertirla en una plataforma que se pueda instalar en otros municipios (e incluso en otros países). 

Mientras sea una aplicación para Madrid únicamente, creemos que las issues y el readme deben estar en castellano porque, lamentablemente, la realidad es que muchos de nuestros conciudadanos aún no se manejan bien con el inglés. Dado que esta herramienta lo que persigue es la involucración ciudadana, primero en Madrid y luego en España, creemos que lo adecuado es que para esta primera fase al menos, tengan las menos trabas posibles.

Cuando pasemos a la fase el plan es moverlo a otra organización y seguramente darle un nombre distinto. Ése será el momento de cambiar todo al inglés.

Una cosa que sí estaríamos dispuestos a hacer sería poner un README.en.md y un CONTRIBUTING.en.md para lectores

**Comment by kikito** [comment]
Y añado: ten en cuenta que acabamos de empezar. Pocas cosas están "escritas en piedra" aún. Lo que te he contado ahora puede que no sea válido mañana

**Comment by piranna** [comment]
> Mientras sea una aplicación para Madrid únicamente, creemos que las issues y el readme deben estar en castellano porque, lamentablemente, la realidad es que muchos de nuestros conciudadanos aún no se manejan bien con el inglés. Dado que esta herramienta lo que persigue es la involucración ciudadana, primero en Madrid y luego en España, creemos que lo adecuado es que para esta primera fase al menos, tengan las menos trabas posibles.

Creo que esto es un error de concepto. Abogo por la participacion ciudadana como el que mas, pero la unica gente que va a tener un minimo de interes en el codigo o en hablar es gente que tiene cuenta en GitHub, y podemos presuponer sin riesgos que es gente que se desenvuelve bien en ingles. Si no es asi, no van a aportar comentarios mas alla del estilo "la interfaz es muy fea, no me gusta". No me parece adecuado que el hecho de que haya mucha gente que no sepa hablar ingles sea motivo para hacer que los issues sean en español, sino que deberia ser cuestiones puramente tecnicas de calidad y estandarizacion, sino estas cerrandole las puertas a mucha gente a que quiera participar y que realmente pueda hacerlo.
