### ISSUE TITLE
Resaltar los comentarios más votados

### ISSUE THREAD

**Issue by Almorca** [AyuntamientoMadrid/participacion#580]
Hay propuestas que tienen comentarios muy votados con ideas muy buenas que pasan desapercibidos ya que no están destacados sobre los demás.

Ese mismo problema surgió hace tiempo en Menéame y se solucionó resaltando los comentarios más votados de manera que la gente los pueda ver echando un rápido vistazo (leer https://gallir.wordpress.com/2011/09/19/el-valor-de-las-opiniones-discordantes/ y https://gallir.wordpress.com/2012/11/29/favorecer-el-disenso/ ). Esto favorece cribar los comentarios intrascendentes y dar más valor a los comentarios que la gente, con su voto, considera que aportan al debate.

**Comment by decabeza** [comment]
Hola @Almorca, ¡gracias por la sugerencia! :+1: 

Cierro este issue ya que esto está en #227 para hacer que los comentarios se ordenen por los más votados :wink:
