### ISSUE TITLE
accesibilidad web

### ISSUE THREAD

**Issue by aldozu** [AyuntamientoMadrid/participacion#603]
Estimado/a. Como ya sabe me llamó Alvaro Domingo yo leyendo su contestación yo creó que la pregunta esta mal formulada, no es lo que vea yo o me preocupe, por mi suerte yo soy discapacitado fisico y no tengo grandes problemas de visión pero si me pongo en la piel de personas que sufren esa minusvalía y lo que si me duele y mucho que con mis impuestos les estoy poniendo más obstaculos, la cuestión no es solo los Catpchas o que este puesta la etiqueta accesskey en el codigo de los hipervinculos interferiendo en los accesos directos del lector de pantalla, lo que de verdad me molesta es que se gasto un dinero se hizo publicidad del nuevo diseño de la web y se olvido y se mintió a las personas.

**Comment by voodoorai2000** [comment]
Estimado Álvaro. Sentimos que te sientas así.
¿Por qué crees que se mintió a las personas?

**Comment by aldozu** [comment]
Se mintió en varios aspectos, se escribió articulos en periodicos comunicando el gasto de 2 millones de euros para mejorar la accesibilidad de la web cosa falsa, se falsea diciendo que esa web ganó el premio a la accesibilidad en 2007, cuando si observan el historial erá distinta, se falsea usando los logos de la W3C, se falsea porque España se rije por la UNE 139803:2012 no por la anterior.

**Comment by voodoorai2000** [comment]
Lo siento, pero creo que no estamos hablando de la misma web. Esta web (https://decide.madrid.es/) empezó a desarrollarse este verano y se lanzó hace poco más de un mes.

**Comment by aldozu** [comment]
Yo hablo de la web del ayuntamiento de Madrid

**Comment by voodoorai2000** [comment]
¿Me puedes escribir el enlace a la web?

**Comment by aldozu** [comment]
Disculpe por no contestar antes en esta url podrá ver las noticias en los
medios
http://ccaa.elpais.com/ccaa/2014/01/06/madrid/1389036146_338501.html
Una de las url que me producen indignacion es:
http://www.madrid.es/portales/munimadrid/es/Inicio/Accesibilidad?vgnextfmt=default&vgnextchannel=1ade43db40317010VgnVCM100000dc0ca8c0RCRD
una de las webs afectadas con los terribles Capthas es.
https://www-s.munimadrid.es/SYR_003_WACiudadanos/iniciar.do?procedimiento=200
Al rellenar no existe el problema el problema viene al confirmar el envio.
Lamento no ser muy preciso. Solo deseó ayudar a las personas.

El 12 de octubre de 2015, 23:53, Raimond Garcia <notifications@github.com>
escribió:

> ¿Me puedes escribir el enlace a la web?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AyuntamientoMadrid/participacion/issues/603#issuecomment-147531727>
> .
>



-- 


Alvaro Domingo Zurdo

Auditor y diseñador web experto en temas de accesibilidad

637520937 www.alvaro-domingo.es

**Comment by voodoorai2000** [comment]
Hola Alberto, siento el retraso en contestar.

Efectivamente hay varias páginas del ayuntamiento. A la que te refieres creo que es https://www-s.munimadrid.es/SYR_003_WACiudadanos/iniciar.do?procedimiento=200. Que es ciertamente muy mejorable.

En cambio http://www.madrid.es/ está muy avanzada a nivel de accesibilidad.

Estamos trabajando para ir mejorando la accesibilidad de todas las webs del Ayuntamiento. Ten paciencia con nosotros y si hay algo que veas importante que mejoremos por favor dínoslo.

Muchas gracias!

**Comment by aldozu** [comment]
Te escribó por varios motivos.
1 me llamó alvaro,jjajaja
2 en la pagina inicial del ayuntamiento la lupa es una image y le falta texto alternativo y función
3 El maximo problema es que la web es un CMD, un gestos de contenido y lo teneis dificil  no imposible.
4 El real decreto 1494/2007 obliga que desde el 2009 ya sea accesible toda web institucional, yo os puedo dar el  tiempo que querais, pero porque no le pides explicaciones a los anteriores administradores,el porque no la hicierón accesible
