### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#624]
Parece que algunos usuarios están teniendo problemas para identificarse.

Nota:
Tiene que ver con el método verifying_via_email? según la excepción 127.

**Comment by kikito** [comment]
Creo que con  https://github.com/AyuntamientoMadrid/participacion/commit/ac1507e85e9c16f834c92eafd0e707d60131ed4c se arregla esto, pero por si acaso dejo la issue abierta. Si la vemos que la excepción 127 no se reproduce, la podemos cerrar
