### ISSUE TITLE
Añadir lista de "temas sugeridos" al crear un debate

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#67]
Cuando se crea un nuevo debate deberían aparecer un listado de "temas sugeridos" o frecuentes que el usuario pueda seleccionar. También podrán añadir etiquetas manualmente en un input del formulario.

![add tags](https://cloud.githubusercontent.com/assets/4169/9134583/c15a223e-3d05-11e5-867d-8502fce4852f.png)

**Comment by xuanxu** [comment]
Closed via #176 :tada:
