### ISSUE TITLE
Respetar los saltos de linea en los comentarios

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#672]
En alguna PR nos hemos comido el código que respeta los saltos de línea en los comentarios.

**Comment by xuanxu** [comment]
Localizado: https://github.com/AyuntamientoMadrid/participacion/pull/644/files#diff-ab7dbdfb2fa4302d21356a0e615620e3

**Comment by voodoorai2000** [comment]
:+1:
