### ISSUE TITLE
ActiveRecord::NoDatabaseError al correr bin/rake db:seed

### ISSUE THREAD

**Issue by rodowi** [AyuntamientoMadrid/participacion#702]
```bash
➜  consulta git:(master) bin/rake db:setup
/Users/r/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:665:in `rescue in connect': FATAL:  database "participacion_development" does not exist
 (ActiveRecord::NoDatabaseError)
```
Es raro porque justamente db:seed debería crear la bd.

Lo solucioné ejecutando `bundle exec rake db:seed` en lugar de `bin/rake ...`

Creo que si otros usuarios tienen problema, se debería actualizar el README con el comando de `bundle exec`, ¿no creen?

**Comment by kikito** [comment]
Hola @rodowi,

El problema es que `bin/rake` presupone que el entorno existe - lo que quiere que la base de datos se ha cargado.

Si te fijas, verás que en el README actual hacemos un `rake db:create` (sin `bin/`) antes del setup. Eso resuelve el problema.

Cierro esta issue por ahora, si tienes más problemas, por favor no dudes en reabrirla.

**Comment by rodowi** [comment]
Gracias @kikito 

Ya no he tenido problemas.
