### ISSUE TITLE
Avatar de usuarios eliminados

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#705]
Sale un poquito descuadrado el avatar del autor de un debate, se queda encima del título del debate.
Ejemplo: https://decide.madrid.es/proposals/2456

**Comment by decabeza** [comment]
Arreglado por https://github.com/AyuntamientoMadrid/participacion/commit/27cdad0a0b8fcfd35fd9c673f1d11fe8f3471152 :clap:
