### ISSUE TITLE
La descripción del debate no está sanitizada

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#71]
Ahora mismo se renderiza como una string normal:

![screen shot 2015-07-31 at 13 36 39](https://cloud.githubusercontent.com/assets/63131/9006579/3aa47e50-3789-11e5-9a04-c37cbe469ac0.png)

Hay que:

* Renderizarla utilizando [sanitize](http://apidock.com/rails/ActionView/Helpers/SanitizeHelper/sanitize)
* Añadir un test que asegure que no admitimos ataques de inyección de javascript

**Comment by andreslucena** [comment]
Creo que pasa lo mismo en la portada por el truncate: 

![captura de pantalla de 2015-08-05 20 56 08](https://cloud.githubusercontent.com/assets/717367/9095400/62546582-3bb7-11e5-9c72-e8db0a484fb8.png)

**Comment by voodoorai2000** [comment]
Grande @andreslucena!

Efectivamente el truncate es un problema si no muestra la etiqueta para cerrar el html necesario.

Aunque creemos que el problema principal es que no estamos utilizando html_safe en la descripción del debate para ese [parcial] (https://github.com/AyuntamientoMadrid/participacion/blob/master/app/views/debates/_debate.html.erb#L13) (creemos que se ha perdido el html_safe al arreglar algún mega-conflict)

Estamos sopesando implementaciones para que la descripción siempre se muestre con html_safe (helper, método en el modelo) y su respectivo test. ¿Cómo ves el asunto?

**Comment by andreslucena** [comment]
El html_safe [está](https://github.com/AyuntamientoMadrid/participacion/blob/master/app/models/debate.rb#L39), no se perdió en los conflicts.

El problema viene por el propio truncate. Por ejemplo en la imagen que pongo el description empieza con un tag `<p>`, por lo que al truncar se rompería porque no estaría el correspondiente `</p>`. Por otro lado el partial que da el problema es [este otro](
https://github.com/AyuntamientoMadrid/participacion/blob/master/app/views/debates/_featured_debate.html.erb#L14).

Se puede probar que el truncate rompe el HTML cambiando esa linea por estas otras: 

```
            <p><%= featured_debate.description %></p>
```
Se ve bien (sin truncar, pero con HTML).

```
            <p><%= truncate(featured_debate.description, length: 200) %></p>
```
Se ve mal (truncado, pero sin HTML).

Se me ocurren dos soluciones:

* Presentar todo el description y hacerlo con CSS (usando text-overflow). Como punto negativo es que aumentaría el peso de HTML, pero deja abierta la funcionalidad de "Ver más...". Esto me parece lo más limpio, y creo que no rompería el HTML. 
* Si puede ser un problema común estudiar de usar esta gema https://github.com/hgmnz/truncate_html o similar.

**Comment by voodoorai2000** [comment]
@andreslucena efectivamente, perdona vamos a mil por hora y se me ha pasado ese commit.

A priori creo que mostrar la descripción entera no afectará al rendimiento si utilizamos bien la caché. Hacerlo con CSS parece lo más elegante. +1

**Comment by voodoorai2000** [comment]
@andreslucena hemos hecho un par de pruebas y al final hemos implementado un degradado con CSS que creemos que resuelve bien el problema.
https://github.com/AyuntamientoMadrid/participacion/pull/102
https://github.com/AyuntamientoMadrid/participacion/pull/102/files#diff-0820efe7ebeabdfea96b2d3c444a3221R322
