### ISSUE TITLE
Insignias de buenas prácticas

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#81]
Configurar y mostrar en los READMEs insignias de buenas prácticas sobre:
  - [x] Calidad del código
  - [x] Últimas versiones de gemas
  - [x] Integración Continua
  - [ ] Cobertura de tests
    
Sugerencias: http://elgalu.github.io/2013/add-achievement-badges-to-your-gem-readme/

**Comment by kikito** [comment]
No podemos utilizar logins de otra gente para acceder a algunos de estos servicios, así que me asigno esta yo.

**Comment by kikito** [comment]
No tengo experiencia con coveralls, así que se la paso a @voodoorai2000 para que la añada

**Comment by xuanxu** [comment]
Closed by #90 and #96
