### ISSUE TITLE
Escoger idioma

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/participacion#82]
Los usuarios deberían poder escoger entre inglés y castellano de una manera simple. La navegación en el resto de enlaces de la aplicación debería ser en el idioma seleccionado.

Sugerencias:
  - http://guides.rubyonrails.org/i18n.html#setting-and-passing-the-locale
  - http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-the-url-params

**Comment by Ferdy89** [comment]
Me la pido! :)

**Comment by kikito** [comment]
Cerrado por #84
