### ISSUE TITLE
Las votaciones no redirigen a hacer login a usuarios anóminos

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#85]
Pasos para reproducir:

* Hacer logout
* Ir a un debate mediante su url (eg /debate/1)
* Intentar votar

Qué ocurre: 
Da un error javascript - *unauthorized*

Qué debería ocurrir:
Cuando un usuario intenta votar sin abrir una sesión la aplicación le debería mostrar el diálogo de login. No deberían producirse errores de javascript.

Sugerencia: si el usuario no está identificado, los links a votar deberían ser links a identificarse (manteniendo como referer la url actual)

**Comment by voodoorai2000** [comment]
![voting not logged in](https://cloud.githubusercontent.com/assets/4169/9175050/cc30f252-3f83-11e5-8000-67b65d385704.png)

**Comment by decabeza** [comment]
@xuanxu he creado el <div class="not-logged"> en el partial "debates/_votes.html.erb". Está subido en la rama **votes**

Este div solo debería aparecer al hacer hover sobre el <div class="votes"> cuando el usuario no esté logueado :smile: 

![not logged featured and list](https://cloud.githubusercontent.com/assets/631897/9202080/54a0fc1e-4050-11e5-921a-ec608be4e2de.png)
![not logged show](https://cloud.githubusercontent.com/assets/631897/9202079/54a03f5e-4050-11e5-8561-9e1e72728163.png)
