### ISSUE TITLE
Añadir clase CSS al votar

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/participacion#88]
Ahora, los botones de apoyar (like/unlike) aparecen siempre de color gris, hay que añadirle una clase CSS (.active-vote, .voted, active..) para poner en color verde o rojo aquellas que ya ha votado el usuario.

**Comment by decabeza** [comment]
También habría que añadir una clase al que el usuario no ha votado, algo como ".no-voted, .disabled..."

**Comment by decabeza** [comment]
De aquí vale la tercera tarjeta (work in progress) ;). La opción que ha votado el usuario se pone de color, y la que no pierde opacidad.

![screen shot 2015-08-05 at 14 01 33](https://cloud.githubusercontent.com/assets/631897/9088430/51ff17b2-3b90-11e5-915b-535b3d1b6499.png)

**Comment by kikito** [comment]
Asignando a @xuanxu porque ya miró esto un poco. @xuanxu, si no puedes o no quieres, pásamelo.

**Comment by xuanxu** [comment]
Ok, yo me encargo
