### ISSUE TITLE
Pseudónimo para usuarios

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#98]
Es deseable que los usuarios puedan participar de forma anónima en algunos procesos de la página.

* Además de los campos de nombre y apellidos, necesitamos un campo "pseudónimo" (o nickname)
* También necesitamos un flag de "usar pseudónimo en lugar de nombre y apellidos". Si está activado, y el pseudónimo está relleno, se utilizará en lugar del nombre y los apellidos.
* El usuario debe ser capaz de cambiar de "usar nombre real" a "usar pseudónimo" y viceversa editando su perfil, además de cuando se da de alta en la aplicación.
* La validación de un usuario pasa a ser: con el flag desactivado, nombre y apellidos son obligatorios. Con el flag activado, el pseudónimo es obligatorio (pero no nombres y apellidos).
* Nótese que el nombre y los apellidos tendrán un papel importante a la hora de aumentar el nivel de seguridad de un usuario, incluso si éste actúa bajo un pseudónimo. No se debe "desactivar la opción de introducir nombre y apellidos" si se activa el flag de pseudónimo.

**Comment by Pi-Po** [comment]
Entendiendo y compartiendo lo que expones, no me queda claro a que nivel de seguridad refieres.

Si estamos tratando de identificar a usuarios con la certeza segura de que un mismo usuario, no invente diferentes accesos con nicks o nombres inventados, sugiero que en algún lugar se incluya algún dato identificativo de curso legal o no que sea único para esa persona.
Puede crearse un identificador o utilizar el número del DNI. No obstante y cómo no hay posibilidad de contrastar la ingente cantidad de personas que pueden acceder y registrarse, es más que probable que el caso de duplicidad por un usuario intencionado aparezca.
