### ISSUE TITLE
Asociaciones

### ISSUE THREAD

**Issue by kikito** [AyuntamientoMadrid/participacion#99]
Deberá ser posible introducir asociaciones en la aplicación.

Las asociaciones son un tipo de usuario que únicamente puede comentar y proponer iniciativas, pero no apoyar iniciativas ni comentarios.

Las asociaciones tienen su propio formulario de alta (accesible desde el formulario de alta por defecto mediante un enlace). Solamente requieren el nombre de la asociación, un email de contacto y un teléfono.

Las asociaciones no se dan de alta inmediatamente, sino que deben ser aprobadas por un administrador. 

Los administradores necesitan una página de administración para aprobar/rechazar este tipo de usuario. Cuando se apruebe una petición de creación de un usuario de tipo Asociación, se le debe enviar un email de confirmación. 

Si el administrador rechaza la petición de la asociación, se les deberá enviar un email informando del rechazo.

**Sugerencias:** Podemos utilizar dos campos booleanos en la tabla de usuarios, `is_organization` y `organization_verifed_at`

**Comment by Pi-Po** [comment]
Sugerencias:

A parte de los datos ya mencionados. Incluir en el alta de las Asociaciones / Fundaciones, su número en vigor del "Registro de Asociaciones / Fundaciones". Además de enviar una copia de su Acta en la cual se recoja su intención de participar y la votación resultante entre todos sus socios.

Los Administradores no podran tomar decisiones unilaterales a este u otros respectos sin la aprobación de la Asamblea de Administradores. En cuyo caso, serán quienes tomen por consenso sus decisiones. En caso contrario, la persona que se salte este procedimiento de transparencia y garantía, deberá acatar la sanción que se decida en la Asamblea de Administradores.

**Comment by kikito** [comment]
Hola @Pi-Po,

De momento el proceso de validación de las asociaciones será simple: los administradores, utilizando el teléfono y el email provisto por la asociación, contactará individualmente a cada una y verificará que son quien dicen ser.

El proceso que propones añadiría complejidad y tiempo de desarrollo que, dadas las limitaciones de tiempo que tenemos, de momento no podemos acometer.

De todas formas, gracias por tus contribuciones.

**Comment by kikito** [comment]
He cambiado de opinión sobre los nombres de los campos: llamémoslos `organization` y `organization_verifed_at`. Podemos hacer evidente que se trata de un booleano utilizando siempre la versión con interrogación en el código (`user.organization?`). Así estaremos alineados con ruby y rails.

**Comment by voodoorai2000** [comment]
+1 user.organization?

**Comment by xuanxu** [comment]
:+1:

**Comment by kikito** [comment]
Me asigno asociaciones

**Comment by kikito** [comment]
Cambio en las spec de esta issue:
* Las organizaciones pueden hacer todo lo que puede hacer una organización en cuanto de dan de alta
* Las organizaciones verificadas por un administrador aparecerán marcadas como "verificadas" visualmente. Esa será la única diferencia.
